### ISSUE TITLE
Add terminal color schemes

### ISSUE THREAD

**Issue by andfoy** [spyder-ide/spyder-terminal#108]
Terminal color schemes should match those of the editor and of the IPython console. I don't know if users should be able to change individually the Terminal color scheme, or if we should follow the behaviour of the IPython console. Any ideas @ccordoba12 @goanpeca ?

**Comment by goanpeca** [comment]
Lets homogenize all the themes in all widgets.

**Comment by ccordoba12** [comment]
> I don't know if users should be able to change individually the Terminal color scheme, or if we should follow the behaviour of the IPython console

The idea is have (eventually) a single color scheme for the entire application. Making the IPython console to follow the Editor was the first step.

So please use the text and background colors of the Editor here too.
