### ISSUE TITLE
Release v0.2.3

### ISSUE THREAD

**Issue by andfoy** [spyder-ide/spyder-terminal#118]

**Comment by dinhe878** [comment]
Thanks! But for some reason I cannot update to v0.2.3 from v0.2.2 via conda. I also try to uninstall and reinstall but the version still remains v0.2.2. Help?

**Comment by andfoy** [comment]
@dinhe878 Sorry, but conda packages are being built right now. Please be patient until they are available.

**Comment by dinhe878** [comment]
Thanks!

**Comment by goanpeca** [comment]
@andfoy [this one](https://github.com/conda-forge/spyder-terminal-feedstock/pull/4) didi ti failed?

**Comment by andfoy** [comment]
@dinhe878 Linux and Windows packages are now available at our anaconda channel. Mac OSX build queue is taking too long.

**Comment by andfoy** [comment]
@goanpeca It didn't fail, I merged it without waiting for the CI build.

**Comment by goanpeca** [comment]
>It didn't fail, I merged it without waiting for the CI build.

Better to not do that next time, cause maybe some errors can occur
