### ISSUE TITLE
Spyder not responding after installing spyder-terminal 

### ISSUE THREAD

**Issue by Mvanti** [spyder-ide/spyder-terminal#119]
## Description of your problem

**What steps will reproduce the problem?**

1.installing spyder-terminal
2.spyder doesn't  connect to the kernel and  freezes
3.

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

## Versions and main components

* Terminal Version:0.2.3
* Spyder Version:3.2.3
* Python Version:3.6
* Operating system:windows 10

<img width="926" alt="spy" src="https://user-images.githubusercontent.com/9116539/31474281-183b4cc0-aed0-11e7-992c-5aa7226d1c48.png">

**Comment by ccordoba12** [comment]
Could you post a screenshot of how Spyder looks after installing spyder-terminal?

**Comment by andfoy** [comment]
@Mvanti Do you have any error message/trace printed on the internal console?

**Comment by Mvanti** [comment]
Nope, I have not been able to install the terminal yet. Spyder hangs after the kernel connection starts.

**Comment by andfoy** [comment]
What's your Qt version?

**Comment by Mvanti** [comment]
Qt5

**Comment by andfoy** [comment]
@ccordoba12 Shall we close also this one?

**Comment by ccordoba12** [comment]
Sure.
