### ISSUE TITLE
Use of non-free Ubuntu fonts

### ISSUE THREAD

**Issue by ghisvail** [spyder-ide/spyder-terminal#120]
`spyder-terminal` uses the Ubuntu font family which is licensed under the Ubuntu Font License. The latter was considered non-free after review by [Debian](https://bugs.launchpad.net/ubuntu-font-licence/+bug/769874) and [Fedora](https://bugzilla.redhat.com/show_bug.cgi?id=961642#c4), and is therefore not suitable for Linux distributions.

Would you consider using an alternative font family which does not suffer from controversial licensing terms, such as `font-awesome`? The latter is already used by `spyder` via `qtawesome`, so it should be a good choice from a consistency perspective.

**Comment by ccordoba12** [comment]
I think FontAwesome is not a character font, isn't it?

**Comment by andfoy** [comment]
@ccordoba12 @ghisvail We could actually switch over to Liberation Mono or some other free font, I didn't know that Ubuntu Fonts had licensing problems

**Comment by andfoy** [comment]
Actually, we're packing Ubuntu fonts only as a working fallback if the user defined mono font is unavailable or the server is running on a Web Browser (Outside Spyder)
