### ISSUE TITLE
Compatibility check: This plugin does not work with Qt 4

### ISSUE THREAD

**Issue by dcasasor** [spyder-ide/spyder-terminal#124]
## Description of your problem

I installed spyder-terminal and got the message shown in the title of this issue when starting Spyder.

**What steps will reproduce the problem?**

1. Install spyder-terminal with pip (sudo pip install spyder-terminal)
2. Open Spyder
3. Get the message

**What is the expected output? What do you see instead?**

The expected output is a third tab at the right hand side of the Spyder window (next to "History log" tab). Instead, the aforementioned message appears and the "File" and "Edit" menus become unuseful.

**Please provide any additional information below**

I tried to install pyqt5 using pip (sudo pip install pyqt5), but pip says "Could not find a version that satisfies the requirement pyqt5". I think that this is because I have Python 2.7 instead of Python 3.

## Versions and main components

* Terminal Version: 0.2.3
* Spyder Version: 3.2.4
* Python Version: 2.7
* Operating system: Linux Mint 18 "Sarah"

**Comment by ccordoba12** [comment]
You need to use pyqt5 and python 3 to use spyder-terminal. There is nothing else we can do to change that.
