### ISSUE TITLE
xterm 3.0 (switched from DOM to canvas)

### ISSUE THREAD

**Issue by stonebig** [spyder-ide/spyder-terminal#126]
Hi all,

I notice a new much more speedy version of Xterm is out, with a motor change
Will it break spyder-Terminal ? 
If not, could you consider using it (given the claimed speed-up) ?

https://github.com/jupyterlab/jupyterlab/issues/3549

**Comment by ccordoba12** [comment]
@andfoy, do you have time to look into this?

**Comment by andfoy** [comment]
@stonebig Thanks for the notice! I'll try to take a look at it during the following weeks, surely before February
