### ISSUE TITLE
Terminal Server could not be located

### ISSUE THREAD

**Issue by billysuyapmo** [spyder-ide/spyder-terminal#127]
## Description of your problem
When I start Spyder, I get an error message that my "Terminal server could  not be located at 127.0.0.1:8071 ......"
**What steps will reproduce the problem?**

1. Starting Spyder
2.
3.

**What is the expected output? What do you see instead?**

**Please provide any additional information below**
I have tried to use SPYDER_DEV and this is my spyder_terminal_err.log 

2018-01-23 11:39:22 DESKTOP-MQ8OL7V __main__[12572] INFO Server is now at: 127.0.0.1:8071
2018-01-23 11:39:22 DESKTOP-MQ8OL7V __main__[12572] INFO Shell: C:\Windows\system32\cmd.exe

and my spyder_terminal_out.log turns out to be empty

## Versions and main components

* Terminal Version:
* Spyder Version: 3.2.4
* Python Version: 3.6.3
* Operating system: Windows

**Comment by andfoy** [comment]
Superseded by #122
