### ISSUE TITLE
terminal not usable

### ISSUE THREAD

**Issue by wwestlake** [spyder-ide/spyder-terminal#129]
## Description of your problem

**What steps will reproduce the problem?**

1. install terminal in Spyder 3.2.6
2. terminal shows up in pane
3. cannot type in terminal at all
4. selecting new terminal from the menu opens a new terminal briefly and then it closes

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

## Versions and main components

* Terminal Version:  
* Spyder Version: 3.2.6
* Python Version: 3.6.4 64 bit
* Operating system: Windows 10

**Comment by ccordoba12** [comment]
What is your operating system?

**Comment by wwestlake** [comment]
windows 10, not sure what terminal version it is, I used pip to install it.

**Comment by ccordoba12** [comment]
And what are Qt/PyQt versions?

**Comment by wwestlake** [comment]
Qt 5 and PyQt 5.6.0, I am running Anaconda3 that I just installed and loading Spyder through Anaconda Navigator

**Comment by andfoy** [comment]
@ccordoba12 Should we close this one also? c.f. #135

**Comment by ccordoba12** [comment]
It doesn't seem like the same problem, but without more details, sure let's close it.

**Comment by nedimm** [comment]
Hi, I have the same problem.
