### ISSUE TITLE
Remove requirement on pexpect for Windows

### ISSUE THREAD

**Issue by ccordoba12** [spyder-ide/spyder-terminal#136]
If understand things correctly, `pexpect` is not needed on Windows because that's what `pywintpy` is for. So we need to remove that requirement from setup.py, appveyor.yml and clarify our Readme.

**Comment by andfoy** [comment]
@ccordoba12 However, pexpect will be removed once we migrate the server backend to terminado

**Comment by ccordoba12** [comment]
Ok, but let's fix this mistake in 0.2.4 as well.
