### ISSUE TITLE
Python 3.7 build for Spyder Terminal

### ISSUE THREAD

**Issue by adodell** [spyder-ide/spyder-terminal#146]
I am curious if there will be a way to run Spyder Terminal plugin with Python 3.7? I cannot install this plugin since I'm using Py3.7, and I am sure this will cause more problems in the future when newer Python releases come out.

![image](https://user-images.githubusercontent.com/11433737/46428173-27fed000-c6f8-11e8-85ca-9cfc08a85d28.png)

Thanks!

**Comment by ccordoba12** [comment]
We have to wait until new pywinpty packages for 3.7 are available in conda-forge:

https://github.com/conda-forge/pywinpty-feedstock/pull/22

Please ping us in a couple of days if we haven't answered here until then.

**Comment by andfoy** [comment]
@adodell we're currently experiencing some problems with our conda recipe build on conda-forge, we expect it to release in 3-days time maximum. Thanks for your patience 
https://github.com/conda-forge/spyder-terminal-feedstock/pull/6#issuecomment-427980224

**Comment by adodell** [comment]
@andfoy no worries, just wondering what was going on, love everything you guys do for the Spyder project

**Comment by ccordoba12** [comment]
Python 3.7 builds for our latest version (0.2.4) are now available in our channel.
