### ISSUE TITLE
How to increase/decrease size of font in terminal?

### ISSUE THREAD

**Issue by danieltomasz** [spyder-ide/spyder-terminal#148]
The standrad way (-/+) which I could use   for zooming  in main window of  Spyder editor doesn't work.
Also changing font  size in General spyder preferences doesn't seem to influence terminal.

**Comment by goanpeca** [comment]
Maybe we could add this on the right click as some other plugins do?

I guess the Ctrl++/- should also work :shrug:

![Screen Shot 2020-05-04 at 16.56.39.png](https://images.zenhubusercontent.com/560c1b40638e718c995d70b3/548fb980-a180-4750-b101-7676c7d748e6)

What do you think about this @steff456?

**Comment by paraschakis** [comment]
That would be super-nice, thank you in advance! My eyes hurt :)

**Comment by ccordoba12** [comment]
@steff456, does xterm.js have an option to do this?

**Comment by steff456** [comment]
This feature is difficult to adjust, because it also changes the font size and the terminal size. Right now, this option is not available. I guess we could add the option for the users to set the font size themselves.

**Comment by ccordoba12** [comment]
> I guess we could add the option for the users to set the font size themselves.

Agreed. Please go ahead with this @steff456.
