### ISSUE TITLE
Spyder-terminal is not starting on spyder 4 beta 2

### ISSUE THREAD

**Issue by steff456** [spyder-ide/spyder-terminal#149]
## Description of your problem

Spyder-terminal plugin is not starting

**What steps will reproduce the problem?**

1. Install current spyder-terminal version
2. Run spyder

**What is the expected output? What do you see instead?**
The spyder-terminal client should start

## Versions and main components

* Terminal Version: 0.2.4
* Spyder Version: 4.0.0.dev0
* Python Version: 3.7
* Operating system: MacOS / Linux / Windows

**Comment by havefun-hh** [comment]
I have the same question.Can't find terminal plugin in spyder.
