### ISSUE TITLE
Add correct localization handling

### ISSUE THREAD

**Issue by goanpeca** [spyder-ide/spyder-terminal#158]
To be able to correctly localize external plugins we need to use `get_translation` method and provide the module name like:

```python
from spyder.config.base import get_translation

_ = get_translation('spyder_terminal')
```

@ccordoba12 maybe we should add a module on the spyder api like or similar

```python
from spyder.api.i18n import get_translation  # Maybe think of a better name :-p for this func
```

**Comment by ccordoba12** [comment]
Sounds good to me.

**Comment by ccordoba12** [comment]
Is this already solved?

**Comment by goanpeca** [comment]
Yep
