### ISSUE TITLE
Some UI/UX improvements for 0.3.0

### ISSUE THREAD

**Issue by goanpeca** [spyder-ide/spyder-terminal#161]
Some comments regarding the terminal that could be addressed in a separate PR but I will list now:

- The panel button does not include the options `Undock`, `Close`
- The panel button looks different than the rest (it has a small arrow)
- It is a bit "weird" to have options for the cursor of the terminal but not for Spyder cursor on the editor itself or the consoles.
- The terminal widget is not showing a blue outline when that panel has the focus (see console bellow)
- We should add a small internal padding or margin if possible to the widget. it looks to crowded

<img width="298" alt="Screen Shot 2019-11-29 at 17 55 40" src="https://user-images.githubusercontent.com/3627835/69892244-83632880-12d1-11ea-84f0-046945cb09c6.png">
Compare to the console
<img width="354" alt="Screen Shot 2019-11-29 at 17 56 16" src="https://user-images.githubusercontent.com/3627835/69892251-8fe78100-12d1-11ea-952b-5e6a4c818f32.png">

**Comment by ccordoba12** [comment]
> The panel button does not include the options Undock, Close
The panel button looks different than the rest (it has a small arrow)

I'll take care of these two.

> It is a bit "weird" to have options for the cursor of the terminal but not for Spyder cursor on the editor itself or the consoles.

I don't know if it's possible to change this in the IPython console, but I wouldn't worry too much about it.

> The terminal widget is not showing a blue outline when that panel has the focus (see console bellow)

This is not working for the Help pane either, so we need to check why the blue outline is not appearing for web widgets. However, I don't see this as blocking for 0.3.0

> We should add a small internal padding or margin if possible to the widget. it looks to crowded

Agreed. @steff456, please add 2 or 3px of padding around the terminal.

**Comment by ccordoba12** [comment]
Another improvement that would be nice to have for 0.3.0 is styling the scrollbar:

![Selección_070](https://user-images.githubusercontent.com/365293/71481607-941d9600-27cc-11ea-936b-d13ae76f6e05.png)

so that it looks like the one in the Help pane

![Selección_071](https://user-images.githubusercontent.com/365293/71481660-ca5b1580-27cc-11ea-97fa-1004b810681f.png)

@dalthviz, please help us with that because you know how to do it.
