### ISSUE TITLE
Spyder terminal does not activate conda environments and keeps asking to "conda init" even after initialization.

### ISSUE THREAD

**Issue by sefademirtas** [spyder-ide/spyder-terminal#164]
## Description of your problem
I use Spyder as part of the Anaconda distribution (which limits the version of Spyder to be 3.3.6). I used conda to install spyder-terminal. First problem is that when I fire up a new terminal window in Spyder, the base conda environment doesn't seem to have been activated with (base) prefix even though "which python" will return the correct path. Then when I try to activate any conda environment (including base), I get a CommandNotFound error asking to use conda init. Even after using "conda init bash" or "conda init --all" and restarting the shell, the CommandNotFound error persists.

**What steps will reproduce the problem?**

1.Start a new terminal.
2. conda activate my_env
3. conda init --all
4. Restart shell
5. conda activate my_env

**What is the expected output? What do you see instead?**
I expect to see my_env activated while both after step #2 and step #5, I see this error message:

_CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
To initialize your shell, run

    $ conda init <SHELL_NAME>

Currently supported shells are:
  - bash
  - fish
  - tcsh
  - xonsh
  - zsh
  - powershell

See 'conda init --help' for more information and options.

IMPORTANT: You may need to close and restart your shell after running 'conda init'._

**Please provide any additional information below**

## Versions and main components

* Terminal Version: native terminal Version 2.8.2
* Spyder Version: 3.3.6
* Python Version: 3.7
* Operating system: Mac OS 10.13.6

**Comment by sefademirtas** [comment]
The previous title did not reflect the issue correctly, so I corrected it.

**Comment by goanpeca** [comment]
Thanks for reporting @sefademirtas, we will look into this in a future release

**Comment by JBum21** [comment]
Any resolution to this issue?

**Comment by JBum21** [comment]
Still having issues with this on macOS 10.15.7

**Comment by janaruto** [comment]
struggling with the same problem, no fixes yet?
