### ISSUE TITLE
Declare DEV mode in tests using conftest.py

### ISSUE THREAD

**Issue by bnavigator** [spyder-ide/spyder-terminal#180]
https://github.com/spyder-ide/spyder-terminal/blob/1797a86ee0f4e94627493b93440b5b99f15437a5/spyder_terminal/terminalplugin.py#L76-L80

https://github.com/spyder-ide/spyder-terminal/blob/1797a86ee0f4e94627493b93440b5b99f15437a5/spyder_terminal/tests/test_terminal.py#L183-L190

The terminal is set up by the fixture `setup_terminal` **before** the `DEV` flag is set manually here. What's the point on that?

Fails on packaging for OpenSUSE because DEV mode is not enabled by default:
```
[   41s] =================================== FAILURES ===================================
[   41s] ___________________________ test_output_redirection ____________________________
[   41s] 
[   41s] setup_terminal = <spyder_terminal.terminalplugin.TerminalPlugin object at 0x7f96cd743280>
[   41s] qtbot_module = <pytestqt.qtbot.QtBot object at 0x7f96cd6d6fa0>
[   41s] 
[   41s]     def test_output_redirection(setup_terminal, qtbot_module):
[   41s]         """Test if stdout and stderr are redirected on DEV mode."""
[   41s]         spyder_terminal.terminalplugin.DEV = True
[   41s]     
[   41s]         stdout = osp.join(getcwd(), 'spyder_terminal_out.log')
[   41s]         stderr = osp.join(getcwd(), 'spyder_terminal_err.log')
[   41s] >       assert osp.exists(stdout) and osp.exists(stderr)
[   41s] E       AssertionError: assert (False)
[   41s] E        +  where False = <function exists at 0x7f96e9e2fe50>('/home/abuild/rpmbuild/BUILD/spyder-terminal-0.3.0/spyder_terminal_out.log')
[   41s] E        +    where <function exists at 0x7f96e9e2fe50> = osp.exists
[   41s] 
[   41s] spyder_terminal/tests/test_terminal.py:189: AssertionError
```

**Comment by ccordoba12** [comment]
I agree with this. The problem @steff456 is that you're declaring `SPYDER_DEV` in our CI scripts, but that doesn't allow to run our test suite independently of them:

https://github.com/spyder-ide/spyder-terminal/blob/71eaf7cdd71d67805786e82d12b1479a40f203e5/.circleci/config.yml

https://github.com/spyder-ide/spyder-terminal/blob/8175e9481b20fc2500f59ec7d0cc2d7da5327508/azure-pipelines.yml

So instead please add a `conftest.py` file in the root of the repo (i.e. next to `setup.py`) that declares that variable using `os.environ` (please see the `conftest.py` in the root of Spyder repo, that declares `SPYDER_PYTEST`). The advantage is that that file is loaded by pytest before running the test suite.

After doing that, please remove setting `SPYDER_DEV` and `DEV` in our CIs and the tests themselves.

**Comment by bnavigator** [comment]
I disagree. This test checks if the program behaves as expected in DEV mode. For that you enable DEV mode. It doesn't necessarily require DEV mode for the whole test suite. There are valid scenarios where you run the test suite not in DEV mode.

So either set the DEV mode before the test, or mark the test to only be run when the whole suite is in DEV mode and accept that this test will not be run for a non DEV mode check.

**Comment by ccordoba12** [comment]
If you disagree please send us a better PR. If not, please let us do our job.

**Comment by ccordoba12** [comment]
Sorry for being so blunt. This is a more detailed answer:

> It doesn't necessarily require DEV mode for the whole test suite

The entire test suite is already running with DEV mode on (that's what setting `SPYDER_DEV` in our CIs does, as the links above show).

> There are valid scenarios where you run the test suite not in DEV mode.

There aren't at the moment, at least not for us.

> So either set the DEV mode before the test, or mark the test to only be run when the whole suite is in DEV mode and accept that this test will not be run for a non DEV mode check.

I'm sorry but I fail to understand why we would need to do that. Since the environment variable will be set in `conftest.py`, it will stop to have effect once `pytest` stops running.

**Comment by bnavigator** [comment]
Ok I misunderstood. I see that in this case the small test suite of spyder-terminal does not have any non DEV mode codepaths. So please disregard my comment above.

**Comment by ccordoba12** [comment]
Thanks for understanding! 👍

**Comment by bnavigator** [comment]
Sorry, but I still have one more recommendation: the (wrong) assignment in line 185 should be removed.
 
> https://github.com/spyder-ide/spyder-terminal/blob/1797a86ee0f4e94627493b93440b5b99f15437a5/spyder_terminal/tests/test_terminal.py#L183-L185

Either remove completely or make it an assertion that DEV was really set by conftest.py

`assert spyder_terminal.terminalplugin.DEV == True`

**Comment by ccordoba12** [comment]
You're totally right! Could you open a new issue or (better yet) submit a PR for that? Thanks!
