### ISSUE TITLE
Create Conda redistribution package

### ISSUE THREAD

**Issue by andfoy** [spyder-ide/spyder-terminal#2]
1. Create conda recipe according to: http://conda.pydata.org/docs/build_tutorials/pkgs.html
2. Test resdistribution using ``conda``

**Comment by ccordoba12** [comment]
I'm working on this one too.

**Comment by ccordoba12** [comment]
I removed this issue from 0.2 because it can only be solved after we release it :-)

So everything is ready to release 0.2, after Spyder 3.2 is released.

**Comment by andfoy** [comment]
@ccordoba12 I think we're ready to upload our conda-build recipe

**Comment by ccordoba12** [comment]
Yes, I think so too. I'll submit a PR against staged-recipes in a couple of days.

Thanks for releasing 0.2.0, by the way ;-)

**Comment by andfoy** [comment]
@ccordoba12 Thanks for the recipe!

**Comment by andfoy** [comment]
After a long way, we finally got to publish our package on conda! https://anaconda.org/spyder-ide/spyder-terminal
