### ISSUE TITLE
Windows Clipboard Paste Problem

### ISSUE THREAD

**Issue by ShayekhBinIslam** [spyder-ide/spyder-terminal#200]
## Description of your problem

**What steps will reproduce the problem?**

1. Open Terminal
2.  Press win-key + V
3.  Press enter

**What is the expected output? What do you see instead?**
Previously Copied String. ^V instead.

**Please provide any additional information below**

## Versions and main components

* Terminal Version:  0.3.0
* Spyder Version: 4.1.2
* Python Version: 3.7.6
* Operating system: Windows 10 Pro

**Comment by goanpeca** [comment]
@steff456 can you confirm this issue?

**Comment by steff456** [comment]
@ShayekhBinIslam did you modify the predetermined shortcut?
The predetermined shortcut for Windows is `Ctrl+Alt+Shift+V` for pasting 
Let me know if it works for you

**Comment by ShayekhBinIslam** [comment]
I did not modify any setting related to the terminal.

I think, I could not make myself clear. I am restating my problem.

Windows allows to paste no only current copied string in clipboard, but also previously copied strings through the button win-key+V. I have no problem with the normal copy-pasting. But I cannot copy from history in the clipboard. Thanks.

**Comment by steff456** [comment]
This will be a feature request, we will take it into account for the next version of the terminal.
In the mean time, please use the normal copy-pasting in the terminal

**Comment by steff456** [comment]
Hi @ShayekhBinIslam,

I tried to add this feature to the terminal, but then I encounter that `Winkey+V` is `Ctrl+V` in Qt. Sadly, `Ctrl+V` is an escape sequence in terminals. So we are not going to override this behavior, please remember that in the preferences section you can change the combination of shortcuts. 

I'm closing this issue.
Thanks for reporting!
