### ISSUE TITLE
Correctly generate logging files

### ISSUE THREAD

**Issue by stuartn60** [spyder-ide/spyder-terminal#206]
## Description of your problem

**What steps will reproduce the problem?**

1. Start Spyder3
2. Few seconds later the error message appears

**What is the expected output? What do you see instead?**
Attached error message

**Please provide any additional information below**

## Versions and main components

* Terminal Version: python3-tornado6 6.0.4-2.1 & python3-terminado 0.8.3-1.4
* Spyder Version:4.1.3
* Python Version: 3.8.3
* Operating system: OpenSuse Tumbleweed
![spyder screen shot](https://user-images.githubusercontent.com/7843758/83128740-2d0b6100-a11f-11ea-87e9-7f4889bf64f0.png)
[spyder-debug.log](https://github.com/spyder-ide/spyder-terminal/files/4694809/spyder-debug.log)

**Comment by ccordoba12** [comment]
Please read with care the message above: we need to logs generated by Spyder terminal, not the ones coming from Spyder itself, to debug this.

**Comment by stuartn60** [comment]
How do I start the terminal in debug mode to obtain the server logs? (sorry to be a bit naive on this)

**Comment by ccordoba12** [comment]
Simply start Spyder in debug mode and the files mentioned in the message should be generated automatically (I think) in your current working directory.

**Comment by stuartn60** [comment]
Thanks ... did that ... I sent the only file that appeared!

**Comment by stuartn60** [comment]
For information: from pypi.org/project/spyder-terminal ... found the issue by running ...
python3 -m spyder_terminal.server --port 8071
... missing colorlogs ... python3-colorlogs ... along with dependencies python3-capturer, python3-humanfriendly, python3-verboselogs
... spyder-terminal log files still missing after running ...
spyder3 --debug-info verbose --debug-output file

**Comment by ccordoba12** [comment]
> .. missing colorlogs ... python3-colorlogs ... along with dependencies python3-capturer, python3-humanfriendly, python3-verboselogs

Please report that to your the distro maintainer for this package.

**Comment by ccordoba12** [comment]
@steff456, I think we need to connect the generation of logging files here with the function `get_debug_level` from Spyder and not with `DEV` (as it is right now, if I'm not mistaken).
