### ISSUE TITLE
Having problems installing spyder-terminal in a conda environment

### ISSUE THREAD

**Issue by map0logo** [spyder-ide/spyder-terminal#209]
## I've tried unsuccessfully to install spyder-terminal in a conda environment

**What steps will reproduce the problem?**

1. To isolate changes I create a brand new environment
```
  $  conda create -n spyder
  $  conda activate spyder
```
2. Then I install Spyder
```
 (spyder) $  conda install -c conda-forge spyder
 (spyder) $  conda install -c conda-forge python-language-server
```
3. And try to install the plugin
```
 (spyder) $  conda install spyder-terminal -c spyder-ide
```

**What is the expected output? What do you see instead?**

Expected output: Successful installation

I got instead a large list of dependencies conflicts

**Please provide any additional information below**

## Versions and main components

* Terminal Version: bash 4.4.20(1)-release
* Spyder Version: 4.1.3
* Python Version:  3.8.3 | packaged by conda-forge
* Operating system: Linux Mint 19.3 Tricia (also Manjaro)

**Comment by steff456** [comment]
Hi @map0logo,

Can you please install spyder from our own channel instead of conda-forge in a new environment?
```
conda create -n my-env python=3
conda install -c spyder-ide spyder=4.1.3
conda install -c spyder-ide spyder-terminal
```

Please let me know if that works for you

**Comment by steff456** [comment]
Closing this issue because there was no followup after 10 days

**Comment by lwbaqueros** [comment]
Hello @steff456, I am having the same problem when trying to install the plugin. I am in Linux Ubuntu with Python 3.8.3 and the following packages:

> **Name**                    **Version**                   **Build  Channel**
> spyder                       4.1.4                      py38_0  
> spyder-kernels          1.9.3                      py38_0  
> spyder-notebook       0.3.0                      py_0    spyder-ide
> spyder-unittest          0.4.1                      py_0    spyder-ide

I tried to install the plugin in a conda environment with  `conda install -c spyder-ide spyder-terminal`

I got the following result:

> Collecting package metadata (current_repodata.json): done
> Solving environment: failed with initial frozen solve. Retrying with flexible solve.
> Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
> Collecting package metadata (repodata.json): done
> Solving environment: failed with initial frozen solve. Retrying with flexible solve.
> Solving environment: / 
> Found conflicts! Looking for incompatible packages.
> This can take several minutes.  Press CTRL-C to abort.
> failed                                                                          
> 
> UnsatisfiableError: The following specifications were found
> to be incompatible with the existing python installation in your environment:
> 
> Specifications:
> 
>   - spyder-terminal -> python[version='>=3.5,<3.6.0a0']
> 
> Your python: defaults/linux-64::python==3.8.3=hcff3b4d_0
> 
> If python is on the left-most side of the chain, that's the version you've asked for.
> When python appears to the right, that indicates that the thing on the left is somehow
> not available for the python version you are constrained to. Note that conda will not
> change your python version to a different minor version unless you explicitly specify
> that.

**Comment by steff456** [comment]
Hi @lwbaqueros,

Thanks for reporting your issue and it seems that you have a problem with your current environment because in conda forge we published a version for python 3.8. Please try to install spyder and spyder-terminal in a new and clean environment to see if the error persists,

`
Conda create -n test python=3.8
Conda activate test
Conda install spyder=4.1.5 spyder-terminal=0.4.2
`

Please let me know how it goes.

**Comment by lwbaqueros** [comment]
Inside the new test enviroment, using `$ conda install spyder-terminal=0.4.2` I got:
> PackagesNotFoundError: The following packages are not available from current channels:
> 
>   - spyder-terminal=0.4.2

and with` conda install -c spyder-ide spyder-terminal` I got the same error about the python version.

**Comment by lwbaqueros** [comment]
`conda config --show channels` Returns  `channels:  - defaults`

**Comment by lwbaqueros** [comment]
Using the channel conda-forge I have installed it successfully. 

`conda install -c conda-forge spyder-terminal`

**Comment by steff456** [comment]
Yes! Sorry, I forgot to add the spyder-ide channel. Do you have the terminal running and working as expected?

**Comment by lwbaqueros** [comment]
Yep, it works great! Thanks for this awesome plugin!!

**Comment by steff456** [comment]
Thanks @lwbaqueros! I'm glad that you like this plugin :)

As your error was fixed I'm going to close this issue. Thanks for reporting!
