### ISSUE TITLE
Shortcuts are not appearing in the preferences pane

### ISSUE THREAD

**Issue by steff456** [spyder-ide/spyder-terminal#218]
## Description of your problem

**What steps will reproduce the problem?**

1. Open preferences > Keyboard shortcuts
2. The terminal options are not listed

**What is the expected output? What do you see instead?**
The terminal option listed so they can be changed

**Comment by ccordoba12** [comment]
Does this need a fix here or in the Spyder repo?

**Comment by goanpeca** [comment]
See: https://github.com/spyder-ide/spyder/wiki/External-Plugins-Shortcut-definition-4.x
