### ISSUE TITLE
Terminal error "ValueError: Invalid cookie 'cwd'"

### ISSUE THREAD

**Issue by dianakozlova** [spyder-ide/spyder-terminal#225]
## Description of my problem

Hi, recently I switched to spyder and downloaded spyder-terminal. It worked fine until today. 
I've tried to commit my changes via git inside the terminal, but what I saw was this: 

![Screenshot 2020-07-02 at 14 21 38](https://user-images.githubusercontent.com/53052173/86358699-3765d100-bc70-11ea-9c8c-34a9b6ab2962.png)

I've tried to uninstall and install the terminal again using
`conda uninstall spyder-terminal -c spyder-ide`
`conda install spyder-terminal -c spyder-ide`
No results.

## Versions and main components

* Terminal Version: spyder-terminal-0.3.1
* Spyder Version: 4.1.3
* Python Version: 3.7.4
* Operating system: IOS 10.14.6

How can I return the functionality?

**Comment by dianakozlova** [comment]
@steff456 could someone help me please?

**Comment by steff456** [comment]
Hi @dianakozlova,

Can you change the directory name to something that doesn't have spaces in it? Please let me know if that fixes the issue, if so, we will add support to directories that have spaces.

**Comment by dianakozlova** [comment]
Dear @steff456, 
Thank you very much, it works now! :) 
It was indeed spacing in my directory naming.

**Comment by steff456** [comment]
We will work on supporting the spaces in our next release, thanks for reporting!

**Comment by MCilento93** [comment]
I append my question to this post to not open a new one.

As optimizing ideas for spyder-terminal I was asking whether you can open the terminal as default in the folder of the spyder project if any.

Thank you,

**Comment by ccordoba12** [comment]
@MCilento93, that's a good idea. Please open a new issue about it.
