### ISSUE TITLE
Update translations

### ISSUE THREAD

**Issue by steff456** [spyder-ide/spyder-terminal#233]
Hello translators! Spyder-Terminal version **0.4.0** is soon to be released and we'd like to ask for your help to update your respective translations.

We plan to do this release on Thursday, so it'd be great if you could help us with that by July 16th 10:00 pm UTC at most. It's ok if you cannot make it on time, we can release your updates on a future version.

## French
@afvincent
@jnsebgosselin 

## Japanese
@sohnishi

## Portuguese (Brazilian)
@sehnem
@manipuladordedados

## Russian
@burrbull
@Qlogin

## Spanish
@ccordoba12
@juanis2112 

## Simplified Chinese
@suokunlong
@kingmo888
@nnnewb
@gepcel

## German
@alexschw
@be-we
@bnavigator 

Best and thanks again!

**Comment by steff456** [comment]
@juanis2112 I already finished the translations for Spanish (:

**Comment by juanis2112** [comment]
Great! Thanks @steff456
