### ISSUE TITLE
Missing import in confpage.py

### ISSUE THREAD

**Issue by pkars** [spyder-ide/spyder-terminal#239]
## Description of your problem
Terminal plugin raises an error when opening Spyder preferences window. The issue is in `confpage.py`:
```
  File "[removed]/spyder_terminal/confpage.py", line 50, in setup_page
    elif sys.platform.startswith('linux'):
NameError: name 'sys' is not defined
```
This prevents setting terminal preferences, too. Adding `import sys` to the file fixes the problem.

**What steps will reproduce the problem?**

1. Use Linux
2. Open Preferences
3.

## Versions and main components

* Terminal Version: 0.3.1
* Spyder Version: 4.1.5
* Python Version: 3.8.5
* Operating system: Ubuntu 18.04.5 LTS

**Comment by steff456** [comment]
Hi @pkars this issue is fixed by #201 and included in the latest release 4.2, to update please type in a console,

```
conda update spyder
conda install spyder-terminal -c spyder-ide
```
