### ISSUE TITLE
Terminal tab not working on spyder 4.1.5, Ubuntu 20.04

### ISSUE THREAD

**Issue by mattip** [spyder-ide/spyder-terminal#240]
### Description of your problem

**What steps will reproduce the problem?**

1. conda create -n spyder python=3.8
2. conda activate spyder
2. conda install spyder
3. conda install spyder-terminal -c spyder-ide
4. spyder

**What is the expected output? What do you see instead?**

I expected to get a functioning terminal with the latest version. I got version 0.3.1. I used `conda install spyder-terminal` to get the latest version. Both version did not seem to work: I see the terminal tab and a blinking box but cannot interact with it. How do I debug what is going on? There is a process `python -m spyder_kernels.console -f /path//kernel-75d692fda5ef.json`, and if I open a new IPython console and connect to that everything seem to work fine.

**Comment by steff456** [comment]
Hi @mattip,

Please update to our latest version 0.4.2 by typing in the console,

```
conda update spyder
conda install spyder-terminal -c spyder-ide
```

If you don't see the terminal tab in Spyder, please go to `View>Panes>Terminal` and it should be visible.

Let me know if this works

**Comment by mattip** [comment]
What channel is spyder 0.4.2 available on? When I search anaconda [I only see 4.1.5](https://anaconda.org/anaconda/spyder). The [installation instructions](https://docs.spyder-ide.org/current/installation.html#new-conda-environment) mention using the conda-forge channel, which I did, but that too only has 4.1.5.

**Comment by mattip** [comment]
Ahh, you meant terminal 0.4.2. That is what I had, your directions downgrade it to 0.3.0:
$ conda install spyder-terminal -c spyder-ide
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /home/matti/miniconda3/envs/spyder

  added / updated specs:
    - spyder-terminal


The following packages will be SUPERSEDED by a higher-priority channel:

  spyder-terminal    conda-forge::spyder-terminal-0.4.2-py~ --> spyder-ide::spyder-terminal-0.3.1-py38h32f6830_1

```

**Comment by mattip** [comment]
I restored it to 0.4.2 by `conda install spyder-terminal=0.4.2`, the problem persists.

**Comment by steff456** [comment]
Can you add a screenshot or gif with the error you are experiencing?

**Comment by mattip** [comment]
Not a lot to see. There is a blinking cursor, the terminal is non-responsive. How can I get debug information? Hoow do I even know if it opened a connection to bash? When I look at the running kernels, and open a new terminal tab, I do not see a new kernel json file created like I do when I open a new IPython-console tab.

![spyder](https://user-images.githubusercontent.com/823911/98333814-3b34a600-200a-11eb-8e95-379ca2531e37.png)
