### ISSUE TITLE
Select+zoom-in-bug & improved graphics

### ISSUE THREAD

**Issue by MCilento93** [spyder-ide/spyder-terminal#241]
## Description of your problem

**What steps will reproduce the problem?**

1. Select all chars in the Terminal
2. Right click with the mouse
3. Click 'zoom-in'

**What is the expected output? What do you see instead?**
I can't see anymore the chars. The cursor instead keeps pulsing and is visible.

**Please provide any additional information below**
I just changed the cursor to be the underscore.

## Versions and main components

* Terminal Version: 0.3.0
* Spyder Version: 4.1.5
* Python Version: 3.7.9
* Operating system: Win 10

More questions:
1. I can't change the color of the highlighted text (now is ugly yellow)
2. The zoom is not so effective on the text: the text is not so clear like the IPython console or Conda Prompt.

**Comment by MCilento93** [comment]
For illustrative purposes, I attach the following.

Thanks for all you job and support.
Sincerely,

![image](https://user-images.githubusercontent.com/66259011/98025476-fe01c580-1e09-11eb-99a6-b392ae378867.png)

**Comment by steff456** [comment]
Hi @MCilento93, this issue was fixed in our latest release, please type the following in a console to update to the latest version,
```
conda update spyder
conda install spyder-terminal -c spyder-ide
```
Thanks for reporting!

**Comment by MCilento93** [comment]
Hello Steff and thank you for helping me.

Unfortunately, now it get worse: I have spyder 4.1.5 with spyder-terminal at 0.3.0 (I didn't succeded to install a later version) and I see a fully black/white screen (without chars, except for the cursor).
Like now, the terminal is not usable anymore.
<img width="365" alt="Immagine 2020-11-06 205927" src="https://user-images.githubusercontent.com/66259011/98409366-f8f37f00-2072-11eb-8185-812ff18ecac7.png">

**Comment by MCilento93** [comment]
I tryied with a fresh environment. 
It does not work with python=3.7 neither python=3.8

For now I keep using GUI bash console :/

**Comment by steff456** [comment]
Hi @MCilento93, this is an error that we are working to fix it and will be available in our next release :D
