### ISSUE TITLE
Terminal just displays a fat cursor and does nothing else

### ISSUE THREAD

**Issue by dkinneyBU** [spyder-ide/spyder-terminal#242]
## Description of your problem
When I open a terminal panel in Spyder, it just displays a fat white cursor and otherwise is unresponsive.

**What steps will reproduce the problem?**
1.Installed spyder-terminal from Anaconda Navigator
2.Opened a terminal panel

**What is the expected output? What do you see instead?**
On my Windows environment I get a cmd prompt. On my ubuntu environment, I just get a "fat" white cursor and the terminal panel is unresponsive.

**Please provide any additional information below**
Everything else in Spyder is working fine--notebook, editor, variable inspector, interactive, etc.

## Versions and main components
* Terminal Version:0.3.1
* Spyder Version:4.1.5
* Python Version:Python 3.8.3
* Operating system:Ubuntu 18.04

![Screenshot from 2020-11-02 18-09-00](https://user-images.githubusercontent.com/43932354/97929519-5ae07b80-1d37-11eb-91c3-6579e886b6df.png)

**Comment by cagatayyildiz** [comment]
I've just upgraded my spyder from 3.* to 4.1.5 and re-installed spyder-terminal, and I had the exact same unresponsive terminal window. Same versions except Python 3.7.0 and macOS 10.15.6

**Comment by steff456** [comment]
Hi @dkinneyBU and @cagatayyildiz, can you please upgrade the terminal to 0.4.2 and let me know if the error persist?

```
conda update spyder
conda install spyder-terminal -c spyder-ide
```

**Comment by dkinneyBU** [comment]
No, I still have the same large square cursor and no response from the terminal. Here is the history from the two commands I ran per your suggestion:

(base) will@will-caster-pinn: ~$ conda update spyder
Collecting package metadata (current_repodata.json): done
Solving environment: | 
The environment is inconsistent, please check the package plan carefully
The following packages are causing the inconsistency:

  - defaults/linux-64::_ipyw_jlab_nb_ext_conf==0.1.0=py38_0
  - defaults/linux-64::widgetsnbextension==3.5.1=py38_0
  - defaults/noarch::jupyterlab_server==1.2.0=py_0
  - conda-forge/noarch::jupyterlab-snippets==0.3.2=pyh9f0ad1d_0
  - conda-forge/noarch::ipywidgets==7.5.1=pyh9f0ad1d_1
  - conda-forge/linux-64::spyder-terminal==0.4.2=py38h32f6830_0
  - conda-forge/noarch::jupyter_contrib_core==0.3.3=py_2
  - conda-forge/linux-64::jupyter_contrib_nbextensions==0.5.1=py38h32f6830_1
  - conda-forge/linux-64::jupyter_nbextensions_configurator==0.4.1=py38h32f6830_2
  - defaults/linux-64::notebook==6.1.4=py38_0
  - defaults/linux-64::spyder==4.1.5=py38_0
  - conda-forge/linux-64::jupyter_latex_envs==1.4.6=py38h32f6830_1001
  - conda-forge/noarch::spyder-memory-profiler==0.2.1=pyh9f0ad1d_1
  - conda-forge/noarch::spyder-notebook==0.3.1=pyhd8ed1ab_0
  - conda-forge/linux-64::jupyter_highlight_selected_word==0.2.0=py38h32f6830_1002
  - defaults/noarch::jupyterlab==2.2.6=py_0
done

## Package Plan ##

  environment location: /home/will/anaconda3

  added / updated specs:
    - spyder


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    ipython-7.19.0             |   py38hb070fc8_0         982 KB
    pip-20.2.4                 |   py38h06a4308_0         1.8 MB
    setuptools-50.3.0          |   py38h06a4308_1         742 KB
    ------------------------------------------------------------
                                           Total:         3.4 MB

The following NEW packages will be INSTALLED:

  nbconvert          pkgs/main/linux-64::nbconvert-6.0.7-py38_0

The following packages will be UPDATED:

  ipython                             7.18.1-py38h5ca1d4c_0 --> 7.19.0-py38hb070fc8_0

The following packages will be DOWNGRADED:

  pip                                         20.2.4-py38_0 --> 20.2.4-py38h06a4308_0
  setuptools                          50.3.0-py38hb0f4dca_1 --> 50.3.0-py38h06a4308_1


Proceed ([y]/n)? y


Downloading and Extracting Packages
ipython-7.19.0       | 982 KB    | ######################################################### | 100% 
pip-20.2.4           | 1.8 MB    | ######################################################### | 100% 
setuptools-50.3.0    | 742 KB    | ######################################################### | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
(base) will@will-caster-pinn: ~$ conda install spyder-terminal -c spyder-ide
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /home/will/anaconda3

  added / updated specs:
    - spyder-terminal


The following packages will be SUPERSEDED by a higher-priority channel:

  spyder-terminal    conda-forge::spyder-terminal-0.4.2-py~ --> spyder-ide::spyder-terminal-0.3.1-py38h32f6830_1


Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
(base) will@will-caster-pinn: ~$ spyder
libpng warning: bKGD: invalid
libpng warning: bKGD: invalid
libpng warning: bKGD: invalid
libpng warning: bKGD: invalid

**Comment by MCilento93** [comment]
Same issue too.
They are figuring this out in next releases

**Comment by steff456** [comment]
Hi @MCilento93,

Can you update to the latest version of spyder-terminal it has the fix for this issue?

**Comment by MCilento93** [comment]
I don't understand, I am on python 3.8.5 but from your setup file I read python >3.5. 
This is the error I got

![image](https://user-images.githubusercontent.com/66259011/99718473-33194380-2aab-11eb-8034-8c681605629a.png)

Spyder just reinstalled at 4.1.5

**Comment by steff456** [comment]
Can you install Spyder 4.2 and then install spyder-terminal? Let me know if this fixes your issue

**Comment by MCilento93** [comment]
Great @steff456 
Solved!!

I can't update spyder right? 
Meaningless but it is ok 👍

**Comment by steff456** [comment]
Normally we are updating the terminal with respect to the latest Spyder version, so it is safe to update it :)

**Comment by MCilento93** [comment]
mmm do you mean I can update spyder to latest??

**Comment by MCilento93** [comment]
if it is already possible I will install spyder-terminal with 4.2. and then update spyder for all the envs I have.
Thank you,
MC

**Comment by dkinneyBU** [comment]
I see that this issue is already closed, but being that I'm the one who opened it, I thought I would just mention that I uninstalled terminal, upgraded Spyder to 4.2, reinstalled terminal and it's working fine now.

Thanks very much for the quick turnaround. I've donated some $ to the cause. :-)

**Comment by steff456** [comment]
Thanks @dkinneyBU! I'm glad we could fix this error and the terminal is working again
