### ISSUE TITLE
Can not see spyder-terminal in Spyder IDE on Windows 10

### ISSUE THREAD

**Issue by kjibran** [spyder-ide/spyder-terminal#248]
I am using Python 3.9.0 and Spyder 4.2.0 on Windows 10 (x64) machine. I installed spyder-terminal and also all its dependencies. But, I can't see the terminal when I open the Spyder IDE.

Here is the output of `pip list`

Package                       Version
----------------------------- ----------
alabaster                     0.7.12
appdirs                       1.4.4
argon2-cffi                   20.1.0
astroid                       2.4.2
async-generator               1.10
atomicwrites                  1.4.0
attrs                         20.3.0
autopep8                      1.5.4
Babel                         2.9.0
backcall                      0.2.0
bcrypt                        3.2.0
black                         20.8b1
bleach                        3.2.1
certifi                       2020.12.5
cffi                          1.14.4
chardet                       4.0.0
click                         7.1.2
cloudpickle                   1.6.0
colorama                      0.4.4
coloredlogs                   15.0
cryptography                  3.3.1
cycler                        0.10.0
decorator                     4.4.2
defusedxml                    0.6.0
diff-match-patch              20200713
docutils                      0.16
entrypoints                   0.3
flake8                        3.8.4
helpdev                       0.7.1
humanfriendly                 9.1
idna                          2.10
imagesize                     1.2.0
intervaltree                  3.1.0
ipykernel                     5.3.4
ipython                       7.19.0
ipython-genutils              0.2.0
ipywidgets                    7.5.1
isort                         5.6.4
jedi                          0.17.2
Jinja2                        2.11.2
joblib                        0.17.0
jsonschema                    3.2.0
jupyter                       1.0.0
jupyter-client                6.1.7
jupyter-console               6.2.0
jupyter-core                  4.7.0
jupyterlab-pygments           0.1.2
keyring                       21.5.0
kiwisolver                    1.3.1
lazy-object-proxy             1.4.3
lxml                          4.6.2
MarkupSafe                    1.1.1
matplotlib                    3.3.3
mccabe                        0.6.1
mistune                       0.8.4
mypy-extensions               0.4.3
nbclient                      0.5.1
nbconvert                     6.0.7
nbformat                      5.0.8
nest-asyncio                  1.4.3
notebook                      6.1.5
numpy                         1.19.4
numpydoc                      1.1.0
packaging                     20.4
pandas                        1.1.4
pandocfilters                 1.4.3
paramiko                      2.7.2
parso                         0.7.0
pathspec                      0.8.1
pexpect                       4.8.0
pickleshare                   0.7.5
Pillow                        8.0.1
pip                           20.3.3
pipdeptree                    1.0.0
pluggy                        0.13.1
prometheus-client             0.9.0
prompt-toolkit                3.0.8
psutil                        5.7.3
ptyprocess                    0.6.0
pycodestyle                   2.6.0
pycparser                     2.20
pydocstyle                    5.1.1
pyflakes                      2.2.0
Pygments                      2.7.2
pylint                        2.6.0
pyls-black                    0.4.6
pyls-spyder                   0.3.0
PyNaCl                        1.4.0
pyparsing                     2.4.7
PyQt5                         5.12.3
PyQt5-sip                     12.8.1
PyQtWebEngine                 5.12.1
pyreadline                    2.1
pyrsistent                    0.17.3
python-dateutil               2.8.1
python-jsonrpc-server         0.4.0
python-language-server        0.36.2
pytz                          2020.4
pywin32                       300
pywin32-ctypes                0.2.0
pywinpty                      0.5.7
pyzmq                         20.0.0
QDarkStyle                    2.8.1
QtAwesome                     1.0.2
qtconsole                     5.0.1
QtPy                          1.9.0
regex                         2020.11.13
requests                      2.25.1
rope                          0.18.0
scikit-learn                  0.23.2
scipy                         1.5.4
seaborn                       0.11.0
Send2Trash                    1.5.0
setuptools                    51.0.0
six                           1.15.0
snowballstemmer               2.0.0
sortedcontainers              2.3.0
Sphinx                        3.3.1
sphinxcontrib-applehelp       1.0.2
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        1.0.3
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.4
spyder                        4.2.1
spyder-kernels                1.10.1
spyder-notebook               0.3.1
spyder-terminal               0.5.0
spyder-unittest               0.4.1
terminado                     0.9.1
testpath                      0.4.4
textdistance                  4.2.0
threadpoolctl                 2.1.0
three-merge                   0.1.1
toml                          0.10.2
tornado                       6.1
traitlets                     5.0.5
typed-ast                     1.4.1
typing-extensions             3.7.4.3
ujson                         4.0.1
urllib3                       1.26.2
watchdog                      1.0.1
wcwidth                       0.2.5
webencodings                  0.5.1
wheel                         0.35.1
widgetsnbextension            3.5.1
wrapt                         1.12.1
xterm                         0.7.3
yapf                          0.30.0

**Comment by steff456** [comment]
Hi @kjibran,

Are you using conda to install the packages or only pip?

**Comment by kjibran** [comment]
Hi @steff456,

I use both (Spyder and its plugins work fine with Conda).

However, the issue I posted was in Python 3.9. I noticed that spyder-terminal doesn't work with Python 3.9, it complains about libraries compatibilities and afterwards, Spyder IDE crashes. Is my observation correct?

I also have Python 3.7 installed and use pip to install packages. Spyder IDE, and spyder-terminal work as expected :)

Cheers,
Jibran

**Comment by steff456** [comment]
Hi @kjibran,

It seems that the terminal is not working because there's not a package of `pywinpty` for Python 3.9. Once it is out, I can let you know to install it and the terminal should be working fine

**Comment by kjibran** [comment]
Hi @steff456,

I can see `pywinpty` for Python 3.9 available at Christoph's Python windows binaries [https://www.lfd.uci.edu/~gohlke/pythonlibs/](url). Is it not the same package we are talking about? I have already this package installed, but spyder-terminal doesn't work.

**Comment by steff456** [comment]
Hi @kjibran,

Earlier today the `pywinpty` 1.0 was released. Can you please upgrade this dependency on your environment and check if spyder-terminal is working?

Right now it is only available in pip, so please use the command `pip install pywinpty==1.0.0`

Let me know if that works for you

**Comment by steff456** [comment]
Hi @kjibran,

Today we released the latest version of spyder-terminal for Spyder 5.0.5. Can you please try it out and let me know if your error still persists?

**Comment by saaketp** [comment]
I am not able to see spyder terminal also in windows 10. Maybe I have the same issue.

I tried running spyder from command prompt and I see:
```
terminal: No module named 'spyder.api.plugin_registration'
Traceback (most recent call last):
  File "D:\ss\Miniconda3\lib\site-packages\spyder\app\solver.py", line 117, in find_external_plugins
    mod = importlib.import_module(entry_point.module_name)
  File "D:\ss\Miniconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "D:\ss\Miniconda3\lib\site-packages\spyder_terminal\__init__.py", line 10, in <module>
    from .terminalplugin import TerminalPlugin as PLUGIN_CLASS
  File "D:\ss\Miniconda3\lib\site-packages\spyder_terminal\terminalplugin.py", line 17, in <module>
    from spyder.api.plugin_registration.decorators import on_plugin_available
ModuleNotFoundError: No module named 'spyder.api.plugin_registration'
```

I installed both `spyder` and `spyder-terminal` from conda-forge. Versions:
```
spyder                    5.0.5            py39hcbf5309_2    conda-forge
spyder-kernels            2.0.5            py39hcbf5309_0    conda-forge
spyder-terminal           1.1.0            py39hcbf5309_0    conda-forge
```

**Comment by saaketp** [comment]
I noticed after posting the comment that there is a new version `spyder=5.1.1` available. I was not able to upgrade because of `python-language-server` installed.

After uninstalling `python-language-server` and installing `spyder` and `spyder-terminal` again this works my system, the terminal is showing up.

**Comment by steff456** [comment]
I'm glad to know that the new version is working as expected @saaketp! 

@kjibran, can you please try it again with the latest version to know if we can resolve this issue and close it?

**Comment by steff456** [comment]
I'm closing this issue because there wasn't a follow-up response after several months. If your error persists please re-open this issue and reply with the requested information.

Thanks for reporting!
