### ISSUE TITLE
Spyder 4.2.1 installed with windows installer: how do we attach spyder-terminal

### ISSUE THREAD

**Issue by dkinneyBU** [spyder-ide/spyder-terminal#249]
## Description of your problem
I installed Spyder 4.2.1 using the new Windows installer. How do I attach spyder-terminal? Anaconda Navigator still thinks I'm running 4.1.4

## Versions and main components

* Terminal Version:
* Spyder Version: 4.2.1
* Python Version: 3.7.9
* Operating system: Windows 10

**Comment by steff456** [comment]
Hi @dkinneyBU,

You'll need to create a new conda environment to install the dependencies that the installer doesn't bring. So in this new environment please install `spyder-terminal`. Then you can go to `Preferences > Python Interpreter > Python Interpreter` and choose the option `Use the following python interpreter` and in the combobox you should be able to see your new environment to connect to Spyder.

![image](https://user-images.githubusercontent.com/20992645/104954062-99302300-5995-11eb-9380-a61bc804bdd8.png)

Please let me know if this works

**Comment by dkinneyBU** [comment]
That worked perfectly. As always, you've come to my rescue. :-)

thanks...
