### ISSUE TITLE
Spyder 5 support

### ISSUE THREAD

**Issue by MuellerSeb** [spyder-ide/spyder-terminal#252]
## Description of your problem

I like this plugin, but it keeps me from using Spyder 5. I am just creating this issue to keep track of the development. I don't want to push anybody. Maybe it could serve as a little motivation, since there are people out there loving this terminal plugin :wink:

**What steps will reproduce the problem?**

1. install spyder 5

**Comment by steff456** [comment]
Hi @MuellerSeb,

This is something I have in my priority list and I hope to soon be working on migrating this plugin to be compatible with Spyder's 5 new API. For now if you want to continue using this plugin please remain working in Spyder 4 and I will close this issue once I make the new release of Spyder-terminal 1.0.0.

Thanks for reporting!

**Comment by MossSekhar** [comment]
Hello, I'm invested in seeing this on Spyder 5. I'm a beginner Python programmer and would like to help. Please let me know if you need anything that I can feasibly do
