### ISSUE TITLE
Spyder-terminal never shows up on menu or as tabbed windows

### ISSUE THREAD

**Issue by richdevboston** [spyder-ide/spyder-terminal#253]
What steps will reproduce the problem?

I have installed Spyder using WinPython 3.9.4 (latest version as of today)

I then installed Spyder-Terminal using conda from the command line.

    install using "conda install spyder-terminal" into environment with Spyder 4.2.1 or Spyder 5.0.1 (I tried both and it does not show up in either Spyder 4.2.1 or 5.0.1.

    Spyder-Terminal never shows up on the menu system under Views.

What is the expected output? What do you see instead?

Spyder-Terminal never shows up on the menu system under Views.
Spyder-Terminal never appears as a tabbed window next to the Spyder Main Editor

Please provide any additional information below (stack trace, screenshots, a gif, etc)

It shows up as being installed in the iPython console inside Spyder v5.0.1:

!conda list spyder-notebook
>> packages in environment at c:\ProgramData\Anaconda3:
>>
> Name                    Version                   Build  Channel
spyder-terminal           0.5.0            py36ha15d459_0    spyder-ide

Versions and main components

    Spyder Version: 5.0.1
    Python Version: Python 3.9.4
    Qt Version: 5.15.1
    PyQt Version: PyQt5 5.15.1
    Jupyter Notebook Version:
    Operating system: Windows 10 Professional

Dependencies

Please go to the menu entry Help > Optional Dependencies (or
Help > Dependencies), press the button Copy to clipboard
and paste the contents below:
Mandatory:

atomicwrites >=1.2.0 : 1.4.0 (OK)
chardet >=2.0.0 : 4.0.0 (OK)
cloudpickle >=0.5.0 : 1.6.0 (OK)
cookiecutter >=1.6.0 : 1.7.2 (OK)
diff_match_patch >=20181111 : 20200713 (OK)
intervaltree >=3.0.2 : 3.0.2 (OK)
IPython >=7.6.0 : 7.22.0 (OK)
jedi =0.17.2 : 0.17.2 (OK)
jsonschema >=3.2.0 : 3.2.0 (OK)
keyring >=17.0.0 : 23.0.1 (OK)
nbconvert >=4.0 : 6.0.7 (OK)
numpydoc >=0.6.0 : 1.1.0 (OK)
paramiko >=2.4.0 : 2.7.2 (OK)
parso =0.7.0 : 0.7.0 (OK)
pexpect >=4.4.0 : 4.8.0 (OK)
pickleshare >=0.4 : 0.7.5 (OK)
psutil >=5.3 : 5.8.0 (OK)
pygments >=2.0 : 2.8.1 (OK)
pylint >=1.0 : 2.7.4 (OK)
pyls >=0.36.2;<1.0.0 : 0.36.2 (OK)
pyls_black >=0.4.6 : 0.4.6 (OK)
pyls_spyder >=0.3.2 : 0.3.2 (OK)
qdarkstyle =3.0.2 : 3.0.2 (OK)
qstylizer >=0.1.10 : 0.1.10 (OK)
qtawesome >=1.0.2 : 1.0.2 (OK)
qtconsole >=5.0.3 : 5.0.3 (OK)
qtpy >=1.5.0 : 1.10.0.dev0 (OK)
setuptools >=39.0.0 : 56.0.0 (OK)
sphinx >=0.6.6 : 3.5.4 (OK)
spyder_kernels >=2.0.1;<2.1.0 : 2.0.1 (OK)
textdistance >=4.2.0 : 4.2.1 (OK)
three_merge >=0.1.1 : 0.1.1 (OK)
watchdog >=0.10.3;<2.0.0 : 1.0.2 (OK)
zmq >=17 : 22.0.3 (OK)

Optional:

cython >=0.21 : 0.29.23 (OK)
matplotlib >=2.0.0 : 3.4.1 (OK)
numpy >=1.7 : 1.20.2 (OK)
pandas >=1.1.1 : 1.2.4 (OK)
scipy >=0.17.0 : 1.6.2 (OK)
sympy >=0.7.3 : 1.8 (OK)

**Comment by dkinneyBU** [comment]
Windows 10 Insider Build 21370, Python 3.7, Spyder 5, installed with anaconda navigator. Also installed spyder-terminal with navigator, same results as above. No terminal pane.

**Comment by steff456** [comment]
Hi @richdevboston and @dkinneyBU, right now spyder-terminal is not working for Spyder 5. If you want to use the pane please stay in Spyder 4 for now. I'm starting to work on the migration and the release of spyder-terminal 1.0.0 this week and hopefully will have the version at the end of this month. 

Thanks for reporting!

**Comment by dkinneyBU** [comment]
Understood—thanks very much for following up! 😊
Dave
