### ISSUE TITLE
spyder 5.0.1 malfunction and time lag between typing and response; or my bad?

### ISSUE THREAD

**Issue by JohannHM** [spyder-ide/spyder-terminal#254]
## Description of your problem
Hi team! Thanks for your efforts.

Look! I use to work with spyder 4.2 but I uploaded to the new 5.0.1, and now a huge lag between typing and spyder screen response appears. The lag is sometimes so big that the whole pc screen gets dark, even if I use another software, e.g., firefox. It takes so much time to take back the control of the keyboard.
It's impossible to work. 

**What steps will reproduce the problem?**

1. when editing code lines, like commenting some library. All methods and functions associated to that library highlight in red (that's normal), but then It's impossible to write any line, or even to move the cursor of either terminal and spyder
2. when commenting some heading line of a code block, like commenting `fig, ax = plt.subplots()`. It generates the same effect described above. Just when uncomment that line everything comes to normal 

**What is the expected output? What do you see instead?**

Just working normally with previous versions. Uncommenting a line shouldn't interfere with writing, or even more with the whole PC's procceses

**Please provide any additional information below**

# Name                    Version                   Build  Channel
pyls-spyder               0.3.2              pyhd3eb1b0_0  
spyder                    5.0.1            py38h578d9bd_0    conda-forge
spyder-kernels            2.0.2            py38h578d9bd_0    conda-forge

## Versions and main components

* Spyder Version:  5.0.1
* Python Version: 3.8
* Operating system: Ubuntu Mate

**Comment by ccordoba12** [comment]
Hey @JohannHM, thanks for reporting. If you downgrade to Spyder 4.2.5 again, is the problem fixed?

**Comment by JohannHM** [comment]
Wow!!!

@ccordoba12, I have several envs in my conda, I upgraded spyder in one of them, just for testing it (off course it was the worst idea, ever). Then when I started to work in my usual environments (4.2), my spyders in those envs completely crashed up!!! The screens of spyder in such envs were a mess: dissorted screen effect, cursor vanished, double or triple tool bars all around the screen!!!! That's why my choice was to totally upgrade to the new version in all envs.
Are your sure that downgrading is the solution?

**Comment by JohannHM** [comment]
Dear @ccordoba12 
Apologize for bothering you. What should be your expertise about both problems above related?
1. spyder 5.0.1 slow down typing when block heading are commented. Relevant when scripting.
2. downgrade spyder version mess the screens up in all environments
Thanks for your recommendation.

**Comment by ccordoba12** [comment]
This is discussed on issue spyder-ide/spyder#15631. Please check it for some helpful pointers.
