### ISSUE TITLE
Spyder Terminal failing on start up

### ISSUE THREAD

**Issue by Joshua-Brooke** [spyder-ide/spyder-terminal#262]
## Description of your problem
On Start up spyder-terminal fails with the error message saying it cannot find the web terminal and asks to open in debug mode.
The terminal does not auto-start and I have to right click to create a new terminal (don't know if this is normal behaviour or just because it fails initially).  If attempting to open before or after the error message different error logs are given in debug mode.

Curiously attempting to edit the installation of pywinpty after the error message restarts the terminal and it works as intended, steps listed in the section below.

**What steps will reproduce the problem?**

1. Wait for error message saying spyder-terminal failed
2. Attempt to modify pywinpty version with pip, successfully uninstalls but fails to install due to winpty.cp39-win_amd64.pyd being busy.  In my case I was switching between 1.1.0 and 1.1.1
3. Right click open spyder terminal

**What is the expected output? What do you see instead?**

**Please provide any additional information below**
#Logs
Opening Terminal before the error appears:
[spyder_terminal_err_before_error.log](https://github.com/spyder-ide/spyder-terminal/files/6583372/spyder_terminal_err_before_error.log)

Opening Terminal before the error appears:
[spyder_terminal_err_after_error.log](https://github.com/spyder-ide/spyder-terminal/files/6583375/spyder_terminal_err_after_error.log)

Output after opening the terminal after modifying pywinpty:
[spyder_terminal_err2.log](https://github.com/spyder-ide/spyder-terminal/files/6583380/spyder_terminal_err2.log)

It seems this forces a restart of the server that lets it work?

## Versions and main components

* Terminal Version: 0.50
* Spyder Version: 4.2.5
* Python Version: 3.9.4
* Operating system: WIndows 10

Thanks in advance for any help!

**Comment by steff456** [comment]
Hi @Joshua-Brooke,

Right now we are updating this plugin to be compatible with Spyder 5 and the latest version of Pywinpty.  I will close this issue once the new version is released for you to try it out.

**Comment by Joshua-Brooke** [comment]
Just to confirm will the updated plugin also work with spyder 4?

**Comment by ccordoba12** [comment]
No, it won't, sorry.

**Comment by steff456** [comment]
Hi @Joshua-Brooke,

We just made the release 1.0.0 for the terminal compatible with Spyder 5.0.5. Please update your Spyder and install the latest version available from pip and conda-forge channel in conda.

As @ccordoba12 already mentioned, this update breaks compatibility with Spyder 4.x.

Thanks for reporting!
