### ISSUE TITLE
Spyder-terminal cannot be installed in Python 3.8 or 3.9

### ISSUE THREAD

**Issue by richdevboston** [spyder-ide/spyder-terminal#269]
## Description of your problem

The Spyder-terminal installer needs to do version checks for Python and Spyder FIRST, warn the user, and stop if they are not using Python 3.6 or Python 3.7.  

We need much clearer documentation for Spyder-Terminal on this Github.com home page too.    It must state WHICH versions of Spyder and Python that Spyder-Terminal v0.5.x requires.  

Right now spyder-terminal installation requires a lot of trial-and-MANY-errors to learn that Spyder-terminal only works with Spyder v4.2 and NOT Spyder v5.0.3.  

You must use Python 3.6 or 3.7 (and NOT v3.8.x or v3.9.x) in a new conda virtual environment, and install spyder-terminal there.

Create a new conda environment with Python 3.6 and install spyder-terminal and spyder-notebook there.  

The correct version of Spyder will be installed along with all of its dependencies.  

Use the following commands...

```
conda create -n python36 -c conda-forge python=3.6
conda install spyder-terminal -c conda-forge spyder-ide
conda install spyder-notebook -c conda-forge spyder-ide
```

**What steps will reproduce the problem?**

1.  try installing into an Anaconda distribution with Python 3.8 or Python 3.9 kernels 
2.  Wait a long time and get many errors.
3.  Rip out a few locks of hair (preferably someone else's)
4.  Start over after you read the instructions above. 

**What is the expected output? What do you see instead?**

errors lost when I closed the installation console

## Versions and main components

* Terminal Version:  spyder-terminal-0.5.0 (spyder-ide/win-64)
* Spyder Version:  '4.2.5'
* Python Version:  3.8 or 3.9 
* Operating system:  Windows 10

**Comment by ccordoba12** [comment]
Hey @richdevboston, thanks for reporting. We'll verify that Spyder-terminal can be installed in those Python versions in our next release.

**Comment by steff456** [comment]
Hi @richdevboston,

We just made the release 1.0.0 for the terminal compatible with Spyder 5.0.5. Please update your Spyder and install the latest version available from pip and conda-forge channel in conda.

Thanks for reporting!

**Comment by richdevboston** [comment]
What versions of Python is this update compatible with?

Thank you.

Best Regards,

Rich Lysakowski, Ph.D.
Data Scientist, Analytics Engineer,
and Senior Business Analyst
781-640-2048 mobile

**Comment by steff456** [comment]
With Python 3.6, 3.7, 3.8 and 3.9
