### ISSUE TITLE
Spyder Terminal doesn't work in Spyder 5.0.4

### ISSUE THREAD

**Issue by Jopinc** [spyder-ide/spyder-terminal#274]
### Description of my problem ###
Spyder terminal is not working in Spyder 5.0.4 based on windows 10 pro and python 3.9.5. More details below.

### Steps #####
1. I have installed Spyder 5.0.4 in Windows 10 Pro using python 3.9.5. I'm not using Anaconda despite I have it installed. 
Then, I installed spyder terminal using "pip" command (pip install spyder-terminal). After that, I open Spyder but the terminal doesn't start and Spyder show me the following message (Spanish): 

    a. Spanish_message:"Su entorno o instalación de Python no cuentan con el módulo spyder‑kernels o con la versión correcta del mismo instalada (>= 2.0.1 y < 2.1.0). Sin este módulo no es posible para Spyder crear una terminal. Puede instalarlo ejecutando en una terminal del sistema:
conda install spyder‑kernels=2.0
o
pip install spyder‑kernels==2.0.* "

    b.English_message: "Your Python environment or installation does not have the spyder-kernels module or the correct version of it installed (> = 2.0.1 and <2.1.0). Without this module it is not possible for Spyder to create a terminal. You can install it by running in a system terminal:
conda install spyder-kernels = 2.0
or
pip install spyder-kernels == 2.0. *"

2. This is the print of "pip" command. 

C:\>pip install spyder-terminal
Requirement already satisfied: spyder-terminal in c:\program files\python39\lib\site-packages (0.5.0)
Requirement already satisfied: tornado in c:\program files\python39\lib\site-packages (from spyder-terminal) (6.1)
Requirement already satisfied: terminado>=0.9.1 in c:\program files\python39\lib\site-packages (from spyder-terminal) (0.10.1)
Requirement already satisfied: coloredlogs in c:\program files\python39\lib\site-packages (from spyder-terminal) (15.0.1)
Requirement already satisfied: spyder<5.0.0,>=4.1.0 in c:\program files\python39\lib\site-packages (from spyder-terminal) (4.2.5)
Requirement already satisfied: requests in c:\program files\python39\lib\site-packages (from spyder-terminal) (2.25.1)
Requirement already satisfied: pyqtwebengine<5.13 in c:\program files\python39\lib\site-packages (from spyder<5.0.0,>=4.1.0->spyder-terminal) (5.12.1)
Requirement already satisfied: qtawesome>=0.5.7 in c:\program files\python39\lib\site-packages (from spyder<5.0.0,>=4.1.0->spyder-terminal) (1.0.3)
Requirement already satisfied: pylint>=1.0 in c:\users\u506706\appdata\roaming\python\python39\site-packages (from spyder<5.0.0,>=4.1.0->spyder-terminal) (2.8.3)
Requirement already satisfied: pyqt5<5.13 in c:\program files\python39\lib\site-packages (from spyder<5.0.0,>=4.1.0->spyder-terminal) (5.12.3)
Collecting spyder-kernels<1.11.0,>=1.10.2
  Using cached spyder_kernels-1.10.3-py2.py3-none-any.whl (65 kB)
Requirement already satisfied: textdistance>=4.2.0 in c:\program files\python39\lib\site-packages (from spyder<5.0.0,>=4.1.0->spyder-terminal) (4.2.1)
Requirement already satisfied: qtpy>=1.5.0 in c:\program files\python39\lib\site-packages (from spyder<5.0.0,>=4.1.0->spyder-terminal) (1.9.0)
Requirement already satisfied: ipython>=7.6.0 in c:\program files\python39\lib\site-packages (from spyder<5.0.0,>=4.1.0->spyder-terminal) (7.24.1)
Requirement already satisfied: watchdog<2.0.0,>=0.10.3 in c:\program files\python39\lib\site-packages (from spyder<5.0.0,>=4.1.0->spyder-terminal) (1.0.2)
Requirement already satisfied: paramiko>=2.4.0 in c:\program files\python39\lib\site-packages (from spyder<5.0.0,>=4.1.0->spyder-terminal) (2.7.2)
Requirement already satisfied: nbconvert>=4.0 in c:\program files\python39\lib\site-packages (from spyder<5.0.0,>=4.1.0->spyder-terminal) (6.0.7)
Requirement already satisfied: pyzmq>=17 in c:\program files\python39\lib\site-packages (from spyder<5.0.0,>=4.1.0->spyder-terminal) (22.1.0)
Requirement already satisfied: setuptools>=39.0.0 in c:\program files\python39\lib\site-packages (from spyder<5.0.0,>=4.1.0->spyder-terminal) (56.0.0)
Requirement already satisfied: cloudpickle>=0.5.0 in c:\program files\python39\lib\site-packages (from spyder<5.0.0,>=4.1.0->spyder-terminal) (1.6.0)
Requirement already satisfied: sphinx>=0.6.6 in c:\program files\python39\lib\site-packages (from spyder<5.0.0,>=4.1.0->spyder-terminal) (4.0.2)
Requirement already satisfied: diff-match-patch>=20181111 in c:\program files\python39\lib\site-packages (from spyder<5.0.0,>=4.1.0->spyder-terminal) (20200713)
Requirement already satisfied: intervaltree>=3.0.2 in c:\program files\python39\lib\site-packages (from spyder<5.0.0,>=4.1.0->spyder-terminal) (3.1.0)
Requirement already satisfied: three-merge>=0.1.1 in c:\program files\python39\lib\site-packages (from spyder<5.0.0,>=4.1.0->spyder-terminal) (0.1.1)
Requirement already satisfied: pexpect>=4.4.0 in c:\program files\python39\lib\site-packages (from spyder<5.0.0,>=4.1.0->spyder-terminal) (4.8.0)
Requirement already satisfied: jsonschema>=3.2.0 in c:\program files\python39\lib\site-packages (from spyder<5.0.0,>=4.1.0->spyder-terminal) (3.2.0)
Requirement already satisfied: pyls-spyder>=0.3.2 in c:\program files\python39\lib\site-packages (from spyder<5.0.0,>=4.1.0->spyder-terminal) (0.4.0)
Requirement already satisfied: chardet>=2.0.0 in c:\program files\python39\lib\site-packages (from spyder<5.0.0,>=4.1.0->spyder-terminal) (4.0.0)
Requirement already satisfied: pygments>=2.0 in c:\program files\python39\lib\site-packages (from spyder<5.0.0,>=4.1.0->spyder-terminal) (2.9.0)
Requirement already satisfied: pickleshare>=0.4 in c:\program files\python39\lib\site-packages (from spyder<5.0.0,>=4.1.0->spyder-terminal) (0.7.5)
Requirement already satisfied: pyls-black>=0.4.6 in c:\program files\python39\lib\site-packages (from spyder<5.0.0,>=4.1.0->spyder-terminal) (0.4.7)
Requirement already satisfied: qtconsole>=5.0.3 in c:\program files\python39\lib\site-packages (from spyder<5.0.0,>=4.1.0->spyder-terminal) (5.1.0)
Requirement already satisfied: psutil>=5.3 in c:\program files\python39\lib\site-packages (from spyder<5.0.0,>=4.1.0->spyder-terminal) (5.8.0)
Requirement already satisfied: parso==0.7.0 in c:\program files\python39\lib\site-packages (from spyder<5.0.0,>=4.1.0->spyder-terminal) (0.7.0)
Requirement already satisfied: python-language-server[all]<1.0.0,>=0.36.2 in c:\program files\python39\lib\site-packages (from spyder<5.0.0,>=4.1.0->spyder-terminal) (0.36.2)
Requirement already satisfied: atomicwrites>=1.2.0 in c:\program files\python39\lib\site-packages (from spyder<5.0.0,>=4.1.0->spyder-terminal) (1.4.0)
Requirement already satisfied: qdarkstyle<3.0,>=2.8 in c:\program files\python39\lib\site-packages (from spyder<5.0.0,>=4.1.0->spyder-terminal) (2.8.1)
Requirement already satisfied: jedi==0.17.2 in c:\program files\python39\lib\site-packages (from spyder<5.0.0,>=4.1.0->spyder-terminal) (0.17.2)
Requirement already satisfied: numpydoc>=0.6.0 in c:\program files\python39\lib\site-packages (from spyder<5.0.0,>=4.1.0->spyder-terminal) (1.1.0)
Requirement already satisfied: keyring>=17.0.0 in c:\program files\python39\lib\site-packages (from spyder<5.0.0,>=4.1.0->spyder-terminal) (23.0.1)
Requirement already satisfied: sortedcontainers<3.0,>=2.0 in c:\program files\python39\lib\site-packages (from intervaltree>=3.0.2->spyder<5.0.0,>=4.1.0->spyder-terminal) (2.4.0)
Requirement already satisfied: colorama in c:\users\u506706\appdata\roaming\python\python39\site-packages (from ipython>=7.6.0->spyder<5.0.0,>=4.1.0->spyder-terminal) (0.4.4)
Requirement already satisfied: decorator in c:\program files\python39\lib\site-packages (from ipython>=7.6.0->spyder<5.0.0,>=4.1.0->spyder-terminal) (4.4.2)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in c:\program files\python39\lib\site-packages (from ipython>=7.6.0->spyder<5.0.0,>=4.1.0->spyder-terminal) (3.0.19)
Requirement already satisfied: matplotlib-inline in c:\program files\python39\lib\site-packages (from ipython>=7.6.0->spyder<5.0.0,>=4.1.0->spyder-terminal) (0.1.2)
Requirement already satisfied: backcall in c:\program files\python39\lib\site-packages (from ipython>=7.6.0->spyder<5.0.0,>=4.1.0->spyder-terminal) (0.2.0)
Requirement already satisfied: traitlets>=4.2 in c:\program files\python39\lib\site-packages (from ipython>=7.6.0->spyder<5.0.0,>=4.1.0->spyder-terminal) (5.0.5)
Requirement already satisfied: six>=1.11.0 in c:\program files\python39\lib\site-packages (from jsonschema>=3.2.0->spyder<5.0.0,>=4.1.0->spyder-terminal) (1.16.0)
Requirement already satisfied: attrs>=17.4.0 in c:\program files\python39\lib\site-packages (from jsonschema>=3.2.0->spyder<5.0.0,>=4.1.0->spyder-terminal) (21.2.0)
Requirement already satisfied: pyrsistent>=0.14.0 in c:\program files\python39\lib\site-packages (from jsonschema>=3.2.0->spyder<5.0.0,>=4.1.0->spyder-terminal) (0.17.3)
Requirement already satisfied: importlib-metadata>=3.6 in c:\program files\python39\lib\site-packages (from keyring>=17.0.0->spyder<5.0.0,>=4.1.0->spyder-terminal) (4.6.0)
Requirement already satisfied: pywin32-ctypes!=0.1.0,!=0.1.1 in c:\program files\python39\lib\site-packages (from keyring>=17.0.0->spyder<5.0.0,>=4.1.0->spyder-terminal) (0.2.0)
Requirement already satisfied: zipp>=0.5 in c:\program files\python39\lib\site-packages (from importlib-metadata>=3.6->keyring>=17.0.0->spyder<5.0.0,>=4.1.0->spyder-terminal) (3.4.1)
Requirement already satisfied: testpath in c:\program files\python39\lib\site-packages (from nbconvert>=4.0->spyder<5.0.0,>=4.1.0->spyder-terminal) (0.5.0)
Requirement already satisfied: nbformat>=4.4 in c:\program files\python39\lib\site-packages (from nbconvert>=4.0->spyder<5.0.0,>=4.1.0->spyder-terminal) (5.1.3)
Requirement already satisfied: entrypoints>=0.2.2 in c:\program files\python39\lib\site-packages (from nbconvert>=4.0->spyder<5.0.0,>=4.1.0->spyder-terminal) (0.3)
Requirement already satisfied: pandocfilters>=1.4.1 in c:\program files\python39\lib\site-packages (from nbconvert>=4.0->spyder<5.0.0,>=4.1.0->spyder-terminal) (1.4.3)
Requirement already satisfied: jupyter-core in c:\program files\python39\lib\site-packages (from nbconvert>=4.0->spyder<5.0.0,>=4.1.0->spyder-terminal) (4.7.1)
Requirement already satisfied: jupyterlab-pygments in c:\program files\python39\lib\site-packages (from nbconvert>=4.0->spyder<5.0.0,>=4.1.0->spyder-terminal) (0.1.2)
Requirement already satisfied: mistune<2,>=0.8.1 in c:\program files\python39\lib\site-packages (from nbconvert>=4.0->spyder<5.0.0,>=4.1.0->spyder-terminal) (0.8.4)
Requirement already satisfied: jinja2>=2.4 in c:\program files\python39\lib\site-packages (from nbconvert>=4.0->spyder<5.0.0,>=4.1.0->spyder-terminal) (3.0.1)
Requirement already satisfied: defusedxml in c:\program files\python39\lib\site-packages (from nbconvert>=4.0->spyder<5.0.0,>=4.1.0->spyder-terminal) (0.7.1)
Requirement already satisfied: bleach in c:\program files\python39\lib\site-packages (from nbconvert>=4.0->spyder<5.0.0,>=4.1.0->spyder-terminal) (3.3.0)
Requirement already satisfied: nbclient<0.6.0,>=0.5.0 in c:\program files\python39\lib\site-packages (from nbconvert>=4.0->spyder<5.0.0,>=4.1.0->spyder-terminal) (0.5.3)
Requirement already satisfied: MarkupSafe>=2.0 in c:\program files\python39\lib\site-packages (from jinja2>=2.4->nbconvert>=4.0->spyder<5.0.0,>=4.1.0->spyder-terminal) (2.0.1)
Requirement already satisfied: nest-asyncio in c:\program files\python39\lib\site-packages (from nbclient<0.6.0,>=0.5.0->nbconvert>=4.0->spyder<5.0.0,>=4.1.0->spyder-terminal) (1.5.1)
Requirement already satisfied: async-generator in c:\program files\python39\lib\site-packages (from nbclient<0.6.0,>=0.5.0->nbconvert>=4.0->spyder<5.0.0,>=4.1.0->spyder-terminal) (1.10)
Requirement already satisfied: jupyter-client>=6.1.5 in c:\program files\python39\lib\site-packages (from nbclient<0.6.0,>=0.5.0->nbconvert>=4.0->spyder<5.0.0,>=4.1.0->spyder-terminal) (6.1.12)
Requirement already satisfied: python-dateutil>=2.1 in c:\program files\python39\lib\site-packages (from jupyter-client>=6.1.5->nbclient<0.6.0,>=0.5.0->nbconvert>=4.0->spyder<5.0.0,>=4.1.0->spyder-terminal) (2.8.1)
Requirement already satisfied: pywin32>=1.0 in c:\program files\python39\lib\site-packages (from jupyter-core->nbconvert>=4.0->spyder<5.0.0,>=4.1.0->spyder-terminal) (301)
Requirement already satisfied: ipython-genutils in c:\program files\python39\lib\site-packages (from nbformat>=4.4->nbconvert>=4.0->spyder<5.0.0,>=4.1.0->spyder-terminal) (0.2.0)
Requirement already satisfied: pynacl>=1.0.1 in c:\program files\python39\lib\site-packages (from paramiko>=2.4.0->spyder<5.0.0,>=4.1.0->spyder-terminal) (1.4.0)
Requirement already satisfied: cryptography>=2.5 in c:\program files\python39\lib\site-packages (from paramiko>=2.4.0->spyder<5.0.0,>=4.1.0->spyder-terminal) (3.4.7)
Requirement already satisfied: bcrypt>=3.1.3 in c:\program files\python39\lib\site-packages (from paramiko>=2.4.0->spyder<5.0.0,>=4.1.0->spyder-terminal) (3.2.0)
Requirement already satisfied: cffi>=1.1 in c:\program files\python39\lib\site-packages (from bcrypt>=3.1.3->paramiko>=2.4.0->spyder<5.0.0,>=4.1.0->spyder-terminal) (1.14.5)
Requirement already satisfied: pycparser in c:\program files\python39\lib\site-packages (from cffi>=1.1->bcrypt>=3.1.3->paramiko>=2.4.0->spyder<5.0.0,>=4.1.0->spyder-terminal) (2.20)
Requirement already satisfied: ptyprocess>=0.5 in c:\program files\python39\lib\site-packages (from pexpect>=4.4.0->spyder<5.0.0,>=4.1.0->spyder-terminal) (0.7.0)
Requirement already satisfied: wcwidth in c:\program files\python39\lib\site-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython>=7.6.0->spyder<5.0.0,>=4.1.0->spyder-terminal) (0.2.5)
Requirement already satisfied: mccabe<0.7,>=0.6 in c:\users\u506706\appdata\roaming\python\python39\site-packages (from pylint>=1.0->spyder<5.0.0,>=4.1.0->spyder-terminal) (0.6.1)
Requirement already satisfied: toml>=0.7.1 in c:\users\u506706\appdata\roaming\python\python39\site-packages (from pylint>=1.0->spyder<5.0.0,>=4.1.0->spyder-terminal) (0.10.2)
Requirement already satisfied: isort<6,>=4.2.5 in c:\users\u506706\appdata\roaming\python\python39\site-packages (from pylint>=1.0->spyder<5.0.0,>=4.1.0->spyder-terminal) (5.9.1)
Requirement already satisfied: astroid==2.5.6 in c:\users\u506706\appdata\roaming\python\python39\site-packages (from pylint>=1.0->spyder<5.0.0,>=4.1.0->spyder-terminal) (2.5.6)
Requirement already satisfied: wrapt<1.13,>=1.11 in c:\users\u506706\appdata\roaming\python\python39\site-packages (from astroid==2.5.6->pylint>=1.0->spyder<5.0.0,>=4.1.0->spyder-terminal) (1.12.1)
Requirement already satisfied: lazy-object-proxy>=1.4.0 in c:\users\u506706\appdata\roaming\python\python39\site-packages (from astroid==2.5.6->pylint>=1.0->spyder<5.0.0,>=4.1.0->spyder-terminal) (1.6.0)
Requirement already satisfied: black>=19.3b0 in c:\program files\python39\lib\site-packages (from pyls-black>=0.4.6->spyder<5.0.0,>=4.1.0->spyder-terminal) (21.6b0)
Requirement already satisfied: regex>=2020.1.8 in c:\program files\python39\lib\site-packages (from black>=19.3b0->pyls-black>=0.4.6->spyder<5.0.0,>=4.1.0->spyder-terminal) (2021.4.4)
Requirement already satisfied: pathspec<1,>=0.8.1 in c:\program files\python39\lib\site-packages (from black>=19.3b0->pyls-black>=0.4.6->spyder<5.0.0,>=4.1.0->spyder-terminal) (0.8.1)
Requirement already satisfied: click>=7.1.2 in c:\program files\python39\lib\site-packages (from black>=19.3b0->pyls-black>=0.4.6->spyder<5.0.0,>=4.1.0->spyder-terminal) (8.0.1)
Requirement already satisfied: appdirs in c:\program files\python39\lib\site-packages (from black>=19.3b0->pyls-black>=0.4.6->spyder<5.0.0,>=4.1.0->spyder-terminal) (1.4.4)
Requirement already satisfied: mypy-extensions>=0.4.3 in c:\program files\python39\lib\site-packages (from black>=19.3b0->pyls-black>=0.4.6->spyder<5.0.0,>=4.1.0->spyder-terminal) (0.4.3)
Requirement already satisfied: python-lsp-server>=1.0.1 in c:\program files\python39\lib\site-packages (from pyls-spyder>=0.3.2->spyder<5.0.0,>=4.1.0->spyder-terminal) (1.1.0)
Requirement already satisfied: PyQt5_sip<13,>=4.19.14 in c:\program files\python39\lib\site-packages (from pyqt5<5.13->spyder<5.0.0,>=4.1.0->spyder-terminal) (12.9.0)
Requirement already satisfied: python-jsonrpc-server>=0.4.0 in c:\program files\python39\lib\site-packages (from python-language-server[all]<1.0.0,>=0.36.2->spyder<5.0.0,>=4.1.0->spyder-terminal) (0.4.0)
Requirement already satisfied: pluggy in c:\program files\python39\lib\site-packages (from python-language-server[all]<1.0.0,>=0.36.2->spyder<5.0.0,>=4.1.0->spyder-terminal) (0.13.1)
Requirement already satisfied: ujson>=3.0.0 in c:\program files\python39\lib\site-packages (from python-language-server[all]<1.0.0,>=0.36.2->spyder<5.0.0,>=4.1.0->spyder-terminal) (4.0.2)
Requirement already satisfied: pydocstyle>=2.0.0 in c:\program files\python39\lib\site-packages (from python-language-server[all]<1.0.0,>=0.36.2->spyder<5.0.0,>=4.1.0->spyder-terminal) (6.1.1)
Requirement already satisfied: pycodestyle<2.7.0,>=2.6.0 in c:\program files\python39\lib\site-packages (from python-language-server[all]<1.0.0,>=0.36.2->spyder<5.0.0,>=4.1.0->spyder-terminal) (2.6.0)
Requirement already satisfied: flake8>=3.8.0 in c:\program files\python39\lib\site-packages (from python-language-server[all]<1.0.0,>=0.36.2->spyder<5.0.0,>=4.1.0->spyder-terminal) (3.8.4)
Requirement already satisfied: yapf in c:\program files\python39\lib\site-packages (from python-language-server[all]<1.0.0,>=0.36.2->spyder<5.0.0,>=4.1.0->spyder-terminal) (0.31.0)
Requirement already satisfied: autopep8 in c:\program files\python39\lib\site-packages (from python-language-server[all]<1.0.0,>=0.36.2->spyder<5.0.0,>=4.1.0->spyder-terminal) (1.5.5)
Requirement already satisfied: pyflakes<2.3.0,>=2.2.0 in c:\program files\python39\lib\site-packages (from python-language-server[all]<1.0.0,>=0.36.2->spyder<5.0.0,>=4.1.0->spyder-terminal) (2.2.0)
Requirement already satisfied: rope>=0.10.5 in c:\program files\python39\lib\site-packages (from python-language-server[all]<1.0.0,>=0.36.2->spyder<5.0.0,>=4.1.0->spyder-terminal) (0.19.0)
Requirement already satisfied: snowballstemmer in c:\program files\python39\lib\site-packages (from pydocstyle>=2.0.0->python-language-server[all]<1.0.0,>=0.36.2->spyder<5.0.0,>=4.1.0->spyder-terminal) (2.1.0)
Requirement already satisfied: python-lsp-jsonrpc>=1.0.0 in c:\program files\python39\lib\site-packages (from python-lsp-server>=1.0.1->pyls-spyder>=0.3.2->spyder<5.0.0,>=4.1.0->spyder-terminal) (1.0.0)
Requirement already satisfied: helpdev>=0.6.10 in c:\program files\python39\lib\site-packages (from qdarkstyle<3.0,>=2.8->spyder<5.0.0,>=4.1.0->spyder-terminal) (0.7.1)
Requirement already satisfied: ipykernel>=4.1 in c:\program files\python39\lib\site-packages (from qtconsole>=5.0.3->spyder<5.0.0,>=4.1.0->spyder-terminal) (5.5.5)
Requirement already satisfied: babel>=1.3 in c:\program files\python39\lib\site-packages (from sphinx>=0.6.6->spyder<5.0.0,>=4.1.0->spyder-terminal) (2.9.1)
Requirement already satisfied: packaging in c:\program files\python39\lib\site-packages (from sphinx>=0.6.6->spyder<5.0.0,>=4.1.0->spyder-terminal) (20.9)
Requirement already satisfied: docutils<0.18,>=0.14 in c:\program files\python39\lib\site-packages (from sphinx>=0.6.6->spyder<5.0.0,>=4.1.0->spyder-terminal) (0.17.1)
Requirement already satisfied: sphinxcontrib-devhelp in c:\program files\python39\lib\site-packages (from sphinx>=0.6.6->spyder<5.0.0,>=4.1.0->spyder-terminal) (1.0.2)
Requirement already satisfied: alabaster<0.8,>=0.7 in c:\program files\python39\lib\site-packages (from sphinx>=0.6.6->spyder<5.0.0,>=4.1.0->spyder-terminal) (0.7.12)
Requirement already satisfied: sphinxcontrib-qthelp in c:\program files\python39\lib\site-packages (from sphinx>=0.6.6->spyder<5.0.0,>=4.1.0->spyder-terminal) (1.0.3)
Requirement already satisfied: sphinxcontrib-applehelp in c:\program files\python39\lib\site-packages (from sphinx>=0.6.6->spyder<5.0.0,>=4.1.0->spyder-terminal) (1.0.2)
Requirement already satisfied: sphinxcontrib-htmlhelp in c:\program files\python39\lib\site-packages (from sphinx>=0.6.6->spyder<5.0.0,>=4.1.0->spyder-terminal) (2.0.0)
Requirement already satisfied: sphinxcontrib-serializinghtml in c:\program files\python39\lib\site-packages (from sphinx>=0.6.6->spyder<5.0.0,>=4.1.0->spyder-terminal) (1.1.5)
Requirement already satisfied: sphinxcontrib-jsmath in c:\program files\python39\lib\site-packages (from sphinx>=0.6.6->spyder<5.0.0,>=4.1.0->spyder-terminal) (1.0.1)
Requirement already satisfied: imagesize in c:\program files\python39\lib\site-packages (from sphinx>=0.6.6->spyder<5.0.0,>=4.1.0->spyder-terminal) (1.2.0)
Requirement already satisfied: pytz>=2015.7 in c:\program files\python39\lib\site-packages (from babel>=1.3->sphinx>=0.6.6->spyder<5.0.0,>=4.1.0->spyder-terminal) (2021.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\program files\python39\lib\site-packages (from requests->spyder-terminal) (1.26.5)
Requirement already satisfied: idna<3,>=2.5 in c:\program files\python39\lib\site-packages (from requests->spyder-terminal) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in c:\program files\python39\lib\site-packages (from requests->spyder-terminal) (2021.5.30)
Requirement already satisfied: pywinpty>=1.1.0 in c:\program files\python39\lib\site-packages (from terminado>=0.9.1->spyder-terminal) (1.1.2)
Requirement already satisfied: webencodings in c:\program files\python39\lib\site-packages (from bleach->nbconvert>=4.0->spyder<5.0.0,>=4.1.0->spyder-terminal) (0.5.1)
Requirement already satisfied: humanfriendly>=9.1 in c:\program files\python39\lib\site-packages (from coloredlogs->spyder-terminal) (9.2)
Requirement already satisfied: pyreadline in c:\program files\python39\lib\site-packages (from humanfriendly>=9.1->coloredlogs->spyder-terminal) (2.1)
Requirement already satisfied: pyparsing>=2.0.2 in c:\program files\python39\lib\site-packages (from packaging->sphinx>=0.6.6->spyder<5.0.0,>=4.1.0->spyder-terminal) (2.4.7)
Installing collected packages: spyder-kernels
  Attempting uninstall: spyder-kernels
    Found existing installation: spyder-kernels 2.0.4
    Uninstalling spyder-kernels-2.0.4:
      Successfully uninstalled spyder-kernels-2.0.4
Successfully installed spyder-kernels-1.10.3

3. As you can see in the print, "pip install" command uninstall spyder-kernel version 2.0.* and install spyder kernel 1.10.*. But then spyder 5.0.4 doesn't work with spyder-kernel 1.10.* and ask me to install version 2.0.*. 

4. When I run the command "pip install spyder‑kernels==2.0.* " as Spyder recomend me, I have the following print with an ERROR:

......some "Requirement already satisfied"...... (my comment)
Installing collected packages: spyder-kernels
  Attempting uninstall: spyder-kernels
    Found existing installation: spyder-kernels 1.10.3
    Uninstalling spyder-kernels-1.10.3:
      Successfully uninstalled spyder-kernels-1.10.3
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
spyder 4.2.5 requires spyder-kernels<1.11.0,>=1.10.2, but you have spyder-kernels 2.0.1 which is incompatible.
Successfully installed spyder-kernels-2.0.1

### Need Help ###
How Can I solve this issue in order to have spyder 5.0.4 working fine with spyder-terminal and spyder-kernel 2.0.*?

Thanks in advanced.

**Comment by steff456** [comment]
Hi @Jopinc,

Right now we are working on the new version for Spyder-terminal that will be available for Spyder 5. We are planning to get this out on the next couple of weeks. Please be patient and if you want to follow the repo so you can see as soon as the release is made to install it.

Thanks for reporting!
