### ISSUE TITLE
terminal doesn't work in spyder ide

### ISSUE THREAD

**Issue by saber-khakbiz** [spyder-ide/spyder-terminal#279]
## Description of your problem

**What steps will reproduce the problem?**

I can't write anything in the terminal!!!

**Please provide any additional information below**
![screenshot_env_spyder](https://user-images.githubusercontent.com/83659641/125109580-ccf43600-e0f8-11eb-8d6c-935e9e0fa14b.png)

## Versions and main components

* Terminal Version: v1.0.0 
* Spyder Version: v5.0.5 (install it with pip)
* Python Version: v3.8.6
* Operating system: 
Edition ->  Windows 10 Pro (64bit)
Version ->  21H1

**Comment by steff456** [comment]
Hi @saber-khakbiz,

Can you let me know what Pywinpty version do you have installed in your environment?

**Comment by saber-khakbiz** [comment]
Hello @steff456,
Version: 1.1.2

**Comment by steff456** [comment]
Can you please update the version to 1.1.3? That should fix your issue :)

**Comment by saber-khakbiz** [comment]
It works now :)
so thanks, @steff456,
