### ISSUE TITLE
Default workdir

### ISSUE THREAD

**Issue by frafra** [spyder-ide/spyder-terminal#285]
## Description of your problem

**What steps will reproduce the problem?**

1. Open the terminal

**What is the expected output? What do you see instead?**

As I am working on a project, I would expect to see the terminal opened on the project folder, not on the home directory.

**Please provide any additional information below**

It would be nice to change the default, or add an option so that the users can decide which folder should be opened by default.

## Versions and main components

* Terminal Version: 1.1.0
* Spyder Version: 5.1.3
* Python Version: 3.9.4
* Operating system: Fedora 34 x86_64

**Comment by steff456** [comment]
Hi @frafra,

The current working directory when you open the terminal is different from your project? We could also add that option to our preferences page for our next release.

**Comment by frafra** [comment]
Hi @steff456,
that is correct. I tried to open spyder with `spyder -p .` and `spyder -p $PWD`, but the working directory is always set to `$HOME`. It would be a nice addition to have it set to the project folder in my opinion, as most of the commands would be executed on the files belonging to the project.

**Comment by steff456** [comment]
In your workflow, there's a way that you have the working directory in a different place than your project?

If so, I'm thinking that currently there's an option to open the terminal in the project directory in the hamburger menu. So maybe I can also add a shortcut to that action.

**Comment by frafra** [comment]
In my workflow, the working directory is always the project main folder. If I really need to browse around, I can use `cd`. Having a different default folder would be like showing the home folder in the directory view (left bar) instead of the project directory, in my opinion; it would look like a suboptimal default to me.

I think that just changing the default would be great, as it would be more consistent with Spyder tools. I see little use case for using a different working directory.

**Comment by ccordoba12** [comment]
I think it's an interesting idea to open new terminals in the current project directory when a project is active. I mean, it's perhaps the most intuitive behavior.
