### ISSUE TITLE
Terminal gets hanged/does'nt responds when its window is resized

### ISSUE THREAD

**Issue by KartikVatsa** [spyder-ide/spyder-terminal#286]
## Description of your problem
When resizing window of terminal inside spyder, terminal no longer responds, the cursor is blinking
but keyboard inputs are not registered. Also when new terminal is created and previous one is deleted,
the whole terminal window goes white and does'nt respond.

**What steps will reproduce the problem?**

1. Open a terminal window (Opens by default). Go to View and unselect lock panes and toolbars
2. Try to resize it, the cursor will blink as if, windows command prompt is responding but keystrokes are not being registered
3. *Get frustrated* Then try to create a new terminal and it gets white all over the window and then nothing responds

**What is the expected output? What do you see instead?**
Terminal does'nt responds and gets hanged. But spyder ide is respoding and working

**Please provide any additional information below**
The only way out is to close the spyder ide and rerun it and avoid resizing any window

## Versions and main components

* Terminal Version: 0.5.0
* Spyder Version: 4.2.5
* Python Version: 3.8.8
* Operating system: Windows 10 Version 20H2 (OS Build 19042.662)

**Comment by steff456** [comment]
Hi @KartikVatsa,

This errors were fixed in our latest version of Spyder Terminal, but it is only compatible with Spyder > 5.1.2. If you can, please update and let me know if the error is not present anymore.

**Comment by steff456** [comment]
I'm closing this issue because there wasn't a follow-up response after more than a week. If your error persists please re-open this issue and reply with the requested information.

Thanks for reporting!
