### ISSUE TITLE
Release v0.1

### ISSUE THREAD

**Issue by andfoy** [spyder-ide/spyder-terminal#29]
First production release of spyder-terminal.

TODO:

* [x] Select ports
* [x] Text overflow
* [x] Terminal names
* [x] Test PyQt 5.8 
* [x] Font selection

**Comment by ccordoba12** [comment]
Tests are failing because Circle doesn't come with `npm`. I'm going to help you with that.

**Comment by andfoy** [comment]
Thanks!

**Comment by ccordoba12** [comment]
I opened #30 to fix our tests ;-)

**Comment by andfoy** [comment]
I will fix the pydocstyle errors, but it seems that the test is timing out

**Comment by ccordoba12** [comment]
Let's move the discussion to #30
