### ISSUE TITLE
Terminal Issue on Spyder 5.1.5

### ISSUE THREAD

**Issue by dhawanrajat15** [spyder-ide/spyder-terminal#292]
## Description of your problem

**What steps will reproduce the problem?**

1. Installed through conda install spyder=5.1.5 to have Terminal window
2. Opening Spyder produces the below error at start.

**What is the expected output? What do you see instead?**
![image](https://user-images.githubusercontent.com/87225630/143238042-f81741eb-cc6b-42ef-b3b0-9784adea4e09.png)

Terminal Server could not be located  at https://127.0.0.18073, please restart Spyder on debugging mode and open an issue with the contents of C:\Users\297739\spyder_terminal_out.log and C:\Users\297739\spyder_terminal_err.log files at https://github.com/spyder_ide/spyder_terminal/issues

**Please provide any additional information below**

## Versions and main components
Package                            VersionNote: you may need to restart the kernel to use updated packages.

---------------------------------- -------------------
alabaster                          0.7.12
altair                             4.1.0
altgraph                           0.16.1
anaconda-client                    1.7.2
anaconda-navigator                 1.9.6
anaconda-project                   0.9.1
appdirs                            1.4.4
argh                               0.26.2
argon2-cffi                        20.1.0
arrow                              0.13.1
asammdf                            5.23.1
asn1crypto                         1.4.0
astroid                            2.5
astropy                            4.2
async-generator                    1.10
atomicwrites                       1.4.0
attrs                              20.3.0
Automat                            20.2.0
autopep8                           1.5.5
Babel                              2.9.0
backcall                           0.2.0
backports.shutil-get-terminal-size 1.0.0
bcrypt                             3.2.0
beautifulsoup4                     4.9.3
binaryornot                        0.4.4
bitarray                           1.6.3
bitstruct                          8.11.0
bkcharts                           0.2
black                              19.10b0
blaze                              0.11.3
bleach                             3.3.0
bokeh                              2.2.3
boto                               2.49.0
Bottleneck                         1.3.2
Brotli                             1.0.9
brotlipy                           0.7.0
canmatrix                          0.9.2
cchardet                           2.1.5
certifi                            2021.10.8
cffi                               1.14.5
chardet                            4.0.0
click                              7.1.2
click-plugins                      1.1.1
cligj                              0.7.2
cloudpickle                        1.6.0
clyent                             1.2.2
colorama                           0.4.4
coloredlogs                        15.0.1
comtypes                           1.1.8
conda                              4.10.3
conda-build                        3.17.6
conda-package-handling             1.7.2
conda-verify                       3.1.1
constantly                         15.1.0
contextlib2                        0.6.0.post1
cookiecutter                       1.7.2
coverage                           5.5
cryptography                       3.3.1
cycler                             0.10.0
Cython                             0.29.21
cytoolz                            0.11.0
dash                               1.19.0
dash-bootstrap-components          0.13.0
dash-core-components               1.15.0
dash-html-components               1.1.2
dash-renderer                      1.9.0
dash-table                         4.11.2
dask                               2021.2.0
datashape                          0.5.4
decorator                          4.4.2
defusedxml                         0.6.0
diff-match-patch                   20200713
distributed                        2021.2.0
docutils                           0.16
entrypoints                        0.3
et-xmlfile                         1.0.1
fastcache                          1.1.0
filelock                           3.0.12
flake8                             3.9.2
Flask                              1.1.2
Flask-Compress                     1.9.0
Flask-Cors                         3.0.10
fsspec                             0.8.3
future                             0.18.2
geojson                            2.5.0
gevent                             21.1.1
glob2                              0.7
gmaps                              0.9.0
gmpy2                              2.0.8
greenlet                           1.0.0
h5py                               2.10.0
HeapDict                           1.0.1
html5lib                           1.1
humanfriendly                      9.2
hyperlink                          21.0.0
hypothesis                         6.14.1
idna                               2.10
imageio                            2.9.0
imagesize                          1.2.0
importlib-metadata                 2.1.1
incremental                        21.3.0
inflection                         0.5.1
iniconfig                          1.1.1
intervaltree                       3.1.0
ipykernel                          5.3.4
ipython                            7.20.0
ipython-genutils                   0.2.0
ipywidgets                         7.6.3
isort                              5.7.0
itsdangerous                       1.1.0
jdcal                              1.4.1
jedi                               0.17.2
Jinja2                             2.11.3
jinja2-time                        0.2.0
joblib                             1.0.1
json5                              0.9.5
jsonschema                         3.2.0
jupyter                            1.0.0
jupyter-client                     6.1.7
jupyter-console                    6.2.0
jupyter-contrib-core               0.3.3
jupyter-contrib-nbextensions       0.5.1
jupyter-core                       4.7.1
jupyter-highlight-selected-word    0.2.0
jupyter-latex-envs                 1.4.4
jupyter-nbextensions-configurator  0.4.1
jupyterlab                         2.2.6
jupyterlab-launcher                0.13.1
jupyterlab-pygments                0.1.2
jupyterlab-server                  1.2.0
jupyterlab-widgets                 1.0.0
jupyterthemes                      0.20.0
kaleido                            0.2.1
keyring                            22.0.1
kiwisolver                         1.3.1
lazy-object-proxy                  1.5.2
lesscpy                            0.14.0
libarchive-c                       2.9
llvmlite                           0.34.0
locket                             0.2.1
lxml                               4.6.2
lz4                                3.1.0
macholib                           1.11
MarkupSafe                         1.1.1
matplotlib                         3.3.4
mccabe                             0.6.1
mdfreader                          3.2
menuinst                           1.4.16
mistune                            0.8.4
mkl-fft                            1.2.1
mkl-random                         1.1.1
mkl-service                        2.3.0
mock                               4.0.3
more-itertools                     8.7.0
mpmath                             1.1.0
msgpack                            1.0.2
multipledispatch                   0.6.0
munch                              2.5.0
mypy-extensions                    0.4.3
mysql-connector-python             8.0.27
natsort                            7.0.1
navigator-updater                  0.2.1
nbclient                           0.5.2
nbconvert                          6.1.0
nbformat                           5.1.2
nest-asyncio                       1.5.1
networkx                           2.5
nltk                               3.5
nose                               1.3.7
notebook                           6.2.0
numba                              0.51.2
numexpr                            2.7.2
numpy                              1.19.2
numpydoc                           1.1.0
odo                                0.5.1
olefile                            0.46
openpyxl                           3.0.6
packaging                          20.9
pandas                             1.2.2
pandas-datareader                  0.10.0
pandocfilters                      1.4.3
paramiko                           2.7.2
parso                              0.7.0
partd                              1.1.0
path                               15.1.0
pathlib2                           2.3.5
pathspec                           0.7.0
pathtools                          0.1.2
patsy                              0.5.1
pefile                             2019.4.18
pep8                               1.7.1
pexpect                            4.8.0
pickleshare                        0.7.5
Pillow                             8.1.0
pip                                21.0.1
pkginfo                            1.7.0
plotly                             4.14.3
pluggy                             0.13.1
ply                                3.11
poyo                               0.5.0
prometheus-client                  0.9.0
prompt-toolkit                     3.0.8
psutil                             5.8.0
ptyprocess                         0.7.0
py                                 1.10.0
py2exe                             0.9.2.2
py4j                               0.10.7
pyasn1                             0.4.8
pyasn1-modules                     0.2.8
PyAutoGUI                          0.9.42
pycodestyle                        2.7.0
pycosat                            0.6.3
pycparser                          2.20
pycrypto                           2.6.1
pycurl                             7.43.0.6
pydocstyle                         5.1.1
pyee                               8.1.0
pyerfa                             1.7.1.1
pyflakes                           2.3.1
PyGetWindow                        0.0.5
Pygments                           2.7.4
PyHamcrest                         2.0.2
PyInstaller                        3.5.dev0+d74052489
pylint                             2.6.0
pyls-spyder                        0.4.0
PyMsgBox                           1.0.6
PyNaCl                             1.4.0
pyodbc                             4.0.0-unsupported
pyOpenSSL                          20.0.1
pyparsing                          2.4.7
pyppeteer                          0.2.5
pyproj                             3.1.0
pyreadline                         2.1
PyRect                             0.1.4
pyrsistent                         0.17.3
PyScreeze                          0.1.21
PySocks                            1.7.1
pyspark                            2.4.4
pytest                             6.2.2
pytest-arraydiff                   0.3
pytest-astropy                     0.8.0
pytest-astropy-header              0.1.2
pytest-cov                         3.0.0
pytest-doctestplus                 0.10.1
pytest-filter-subpackage           0.1.1
pytest-mock                        3.6.1
pytest-openfiles                   0.5.0
pytest-remotedata                  0.3.2
python-dateutil                    2.8.1
python-jsonrpc-server              0.4.0
python-lsp-black                   1.0.0
python-lsp-jsonrpc                 1.0.0
python-lsp-server                  1.2.4
python-slugify                     5.0.2
PyTweening                         1.0.3
pytz                               2021.1
PyWavelets                         1.1.1
pywin32                            227
pywin32-ctypes                     0.2.0
pywinauto                          0.6.6
pywinpty                           0.5.7
PyYAML                             5.4.1
pyzmq                              20.0.0
QDarkStyle                         3.0.2
qstylizer                          0.1.10
QtAwesome                          1.0.3
qtconsole                          5.1.1
QtPy                               1.9.0
regex                              2020.11.13
requests                           2.25.1
retrying                           1.3.3
rope                               0.18.0
Rtree                              0.9.7
ruamel-yaml                        0.15.87
scikit-image                       0.17.2
scikit-learn                       0.23.2
scipy                              1.6.0
seaborn                            0.11.1
selenium                           3.141.0
Send2Trash                         1.5.0
service-identity                   18.1.0
setuptools                         52.0.0.post20210125
Shapely                            1.7.1
simplegeneric                      0.8.1
singledispatch                     3.4.0.3
six                                1.15.0
snowballstemmer                    2.1.0
sortedcollections                  2.1.0
sortedcontainers                   2.3.0
soupsieve                          2.1
Sphinx                             3.4.3
sphinxcontrib-applehelp            1.0.2
sphinxcontrib-devhelp              1.0.2
sphinxcontrib-htmlhelp             1.0.3
sphinxcontrib-jsmath               1.0.1
sphinxcontrib-qthelp               1.0.3
sphinxcontrib-serializinghtml      1.1.4
sphinxcontrib-websupport           1.2.4
spyder                             5.1.5
spyder-kernels                     2.1.3
spyder-terminal                    1.0.0
SQLAlchemy                         1.3.23
statsmodels                        0.12.1
sympy                              1.7.1
tables                             3.6.1
tblib                              1.7.0
terminado                          0.9.2
testpath                           0.4.4
text-unidecode                     1.3
textdistance                       4.2.1
threadpoolctl                      2.1.0
three-merge                        0.1.1
tifffile                           2020.10.1
tinycss                            0.4
tkcalendar                         1.4.0
toml                               0.10.1
toolz                              0.11.1
tornado                            6.1
tqdm                               4.56.0
traitlets                          5.0.5
trajectory                         0.1.1
Twisted                            21.7.0
twisted-iocpsupport                1.0.1
typed-ast                          1.4.2
typing-extensions                  3.7.4.3
ujson                              4.0.2
unicodecsv                         0.14.1
Unidecode                          1.2.0
UNKNOWN                            0.0.0
urllib3                            1.26.3
vega-datasets                      0.9.0
watchdog                           1.0.2
wcwidth                            0.2.5
webencodings                       0.5.1
websockets                         8.1
Werkzeug                           1.0.1
wheel                              0.36.2
whichcraft                         0.6.1
widgetsnbextension                 3.5.1
win-inet-pton                      1.1.0
win-unicode-console                0.5
wincertstore                       0.2
wrapt                              1.12.1
xlrd                               2.0.1
XlsxWriter                         1.3.7
xlwings                            0.22.0
xlwt                               1.3.0
yapf                               0.30.0
zict                               2.0.0
zipp                               3.4.0
zope.event                         4.5.0
zope.interface                     5.2.0

* Terminal Version: 
* Spyder Version: Spyder IDE 5.1.5
* Python Version: Python 3.7.3 64-bit
* Operating system: Windows 7

**Comment by steff456** [comment]
Hi @dhawanrajat15,

Which version of spyder-terminal do you have installed in that environment?

**Comment by dhawanrajat15** [comment]
pip show spyder-terminal
Name: spyder-terminalNote: you may need to restart the kernel to use updated packages.

Version: 1.0.0
Summary: Spyder Plugin for displaying a virtual terminal (OS independent) inside the main Spyder window
Home-page: https://github.com/spyder-ide/spyder-terminal
Author: Spyder Project Contributors
Author-email: spyder.python@gmail.com
License: MIT
Location: c:\programdata\anaconda\lib\site-packages
Requires: coloredlogs, requests, tornado, terminado, spyder
Required-by:

**Comment by steff456** [comment]
Can you update to Spyder-terminal 1.1.0? That should fix this error
