### ISSUE TITLE
Prevent running this plugin if Spyder is using PyQt4

### ISSUE THREAD

**Issue by ccordoba12** [spyder-ide/spyder-terminal#31]
This is an important thing to do and something I forgot to mention before. This is because PyQt4 uses a websockets version that is too old for modern standards.

The plugin should deactivate itself and show a warning message in that case.

**Comment by andfoy** [comment]
How do I indicate Spyder to discard the plugin if PyQt version is lower than 5?

**Comment by ccordoba12** [comment]
I don't think it's necessary to do it in Spyder, I think it can be done here.

You could not declare `PLUGIN_CLASS` in `spyder_terminal/__init__.py` if running in PyQt4. You can use the `PYQT5` constant of qtpy for that.
