### ISSUE TITLE
Spyder crashes after installation of Spyder_terminal

### ISSUE THREAD

**Issue by whmsft** [spyder-ide/spyder-terminal#314]
## Description of my problem

I installed spyder-terminal and spyder failed to open and crashes

**What steps will reproduce the problem?**

1. installed spyder-terminal via pip
2. opened spyder
3. it crashes

**What is the expected output? What do you see instead?**
Expected: spyder shall open
Reality: Spyder is not responding or simply crashed

## Versions and main components

* Terminal Version: 1.2.1
* Spyder Version: 5.2.2
* Python Version: 3.8.10
* Operating system: Windows 7 Home Basic x64

**Comment by steff456** [comment]
Hi @whmsft,

Sadly one of our libraries for windows `pywinpty` only supports versions greater than Windows 10 given that Windows 7 reached end of life. I recommend you to update to a latest windows version.

There's nothing else we can do on our end, sorry
