### ISSUE TITLE
Spyder Terminal shows an error message

### ISSUE THREAD

**Issue by gizemkar** [spyder-ide/spyder-terminal#322]
I have installed Esri Arcgis Pro and I tried to plug-in Spyder to my environment. I was asked to update Conda Spyder to v5.30. I have done it and then I got terminal error "Terminal error couldn't be located at http://127.0.0.1:8071, please restart Spyder on debugging mode and open an issue with the contents of None and None files at https://github.com/spyder-ide/spyder-terminal/issues.

How can I fix it?

![terminal error](https://user-images.githubusercontent.com/104547434/166512948-102cc2e6-facb-4e71-96d7-6c00bb93dc62.PNG)
 

Thank you,
Gizem

**Comment by steff456** [comment]
Hi @gizemkar!

What version of spyder terminal do you have installed? Also, how are you installing it?

**Comment by dalthviz** [comment]
Closing as superseded by #336
