### ISSUE TITLE
Spyder Terminal Error

### ISSUE THREAD

**Issue by sh99-git** [spyder-ide/spyder-terminal#324]
## Description of your problem

**What steps will reproduce the problem?**

1. start spyder

**What is the expected output? What do you see instead?**
I expect terminal to run in spyder. Instead I see error saying
![image](https://user-images.githubusercontent.com/85927442/168243606-203088b7-17a7-4357-a668-36a85664db00.png)

**Please provide any additional information below**
- When I visit http://127.0.0.1:8073 I can access terminal through web. But I cannot see terminal window in ide itself.

- Contents of C:\Users\297739\spyder_terminal_err.log:
  - No QCoreApplication instance found. Application patches not applied. You have to call load_stylesheet function after instantiation of QApplication to take effect. 
  - [32m2022-05-13 13:43:37[0m [35mINPUNWLX0125[0m [34m__main__[11540][0m [1;30mINFO[0m Server is now at: 127.0.0.1:8073
  - [32m2022-05-13 13:43:37[0m [35mINPUNWLX0125[0m [34m__main__[11540][0m [1;30mINFO[0m Shell: C:\windows\system32\cmd.exe

- Contents of C:\Users\297739\spyder_terminal_out.log:
  - blank file

## Versions and main components

* Terminal Version: 1.2.2
* Spyder Version: 5.3.0
* Python Version: 3.9.12
* Operating system: Windows 10 Enterprise

**Comment by steff456** [comment]
Hi @sh99-git,

How did you installed Spyder and Spyder-terminal?

**Comment by sh99-git** [comment]
Through anaconda prompt with pip install spyder spyder-terminal

**Comment by sh99-git** [comment]
I use conda to manage packages. I have tried installing spyder in test environments as you have suggested. But issue still persists.

**Comment by steff456** [comment]
Did you try it on a clean environment using the conda-forge channel?

**Comment by sh99-git** [comment]
Yes. I had tried with clean environment.

**Comment by dalthviz** [comment]
Closing as superseded by #336
