### ISSUE TITLE
Spyder Terminal Error

### ISSUE THREAD

**Issue by Bzheng2020** [spyder-ide/spyder-terminal#328]
## Description of your problem

**What steps will reproduce the problem?**

1. Start Spyder
2.
3.

**What is the expected output? What do you see instead?**

"Spyder Terminal Error: Terminal server could not be located at http://127.0.0.1:8071, please restart Spyder on Debugging mode and open an issue with contents of None and None files at https://github.com/spyder-ide/spyder-terminal/issues"

**Please provide any additional information below**

## Versions and main components

* Terminal Version:
* Spyder Version: 5.3.1
* Python Version: 3.8.10
* Operating system: Windows 10
![Spyder Terminal Error](https://user-images.githubusercontent.com/77287790/176022176-163f3b18-7365-4466-93be-50168150c089.PNG)

**Comment by dalthviz** [comment]
Closing as superseded by #336
