### ISSUE TITLE
Terminal server could not be located

### ISSUE THREAD

**Issue by GregoryMandell** [spyder-ide/spyder-terminal#330]
## Description of your problem

**What steps will reproduce the problem?**

1.Opening Spyder
2.
3.

**What is the expected output? What do you see instead?**

**Please provide any additional information below**
I got an error message that said the terminal server could not be located at http://127.0.0.1:8071.  I was then instructed to restart Spyder in debugging mode, but that didn't solve the problem.  I was also instructed to open an issue.  The problem wasn't present yesterday was I was in the company office.  Today, I am working from home, and I suspect that might have something to do with this issue, although I can't be sure.
![SpyderErrorMessage](https://user-images.githubusercontent.com/113142607/189226109-4965ba8e-7da5-4cbb-a03e-e07f3c819634.jpg)

## Versions and main components

* Terminal Version:
* Spyder Version:
* Python Version:
* Operating system:
![SpyderErrorMessage](https://user-images.githubusercontent.com/113142607/189225820-7fc754a6-8000-4a81-ad01-b90075dbcabf.jpg)

**Comment by dalthviz** [comment]
Closing as superseded by #336
