### ISSUE TITLE
No module named 'flask_sqlalchemy'

### ISSUE THREAD

**Issue by GregoryMandell** [spyder-ide/spyder-terminal#332]
## Description of your problem

**What steps will reproduce the problem?**

1.  Running this line:  from flask_sqlalchemy import SQLAlchemy
2.
3.

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

## Versions and main components

* Terminal Version:
* Spyder Version:
![Spyder_Error_Message_SQL_Alchemy](https://user-images.githubusercontent.com/113142607/189450197-8fc1a652-7342-43c6-b012-ccae70554e3c.jpg)

* Python Version:
* Operating system:

**Comment by ccordoba12** [comment]
Hey @GregoryMandell, thanks for reporting. Just click on the link called `this FAQ` and follow the instructions there.
