### ISSUE TITLE
Spyder crashes everytime when opening

### ISSUE THREAD

**Issue by Kaio1991** [spyder-ide/spyder-terminal#339]
## Description of your problem
I upgraded on Windows Server 2016 Datacenter to Spyder 5.4.0 Standalone. After the upgrade every time I want to open Spyder IDE 
**What steps will reproduce the problem?**

1. Open Spyder
2.  The Initialization Window open and load different things. 
3. After "Loading Working Directory" for a minimal period of time i can see the error message shown below. After that it is closed. 

**What is the expected output? What do you see instead?**
Unfortunately, the library that spyder-terminal use to create terminals is failing to work in your system. Therefore, this plugin will be deactivated. This usually happens on Windows 7 Systems. If that's the case, please consider updating to newer windows version.

**Please provide any additional information below**
 System has been rebooted already.

## Versions and main components

* Spyder Version: 5.4.0
* Python Version: 3.8 (included in Spyder Standalone Installer)
* Operating system: Windows Server 2016 Datacenter

**Comment by Lebsasha** [comment]
I also experiencing this problem. I have Spyder version 5.4.3 , Python 3.10, OS: Windows 10

**Comment by ccordoba12** [comment]
Sorry for the inconvenience. If you're using our Windows installer, you'll be pleased to know that we'll remove Spyder-terminal from it in our next version (5.5.0), to be released in a couple of months.

If not, please uninstall Spyder-terminal to get Spyder working again.
