### ISSUE TITLE
Move terminal webview to be inside a QFrame so that dock panes in Spyder are uniform

### ISSUE THREAD

**Issue by goanpeca** [spyder-ide/spyder-terminal#47]

**Comment by andfoy** [comment]
In it's current state, the webview is embedded inside a QFrame [spyder_terminal/widgets/terminalgui.py#L26](https://github.com/spyder-ide/spyder-terminal/blob/master/spyder_terminal/widgets/terminalgui.py#L26)

**Comment by rlaverde** [comment]
I think that @goanpeca was making reference to use this `spyder.widgets.browser.FrameWebView `https://github.com/spyder-ide/spyder/blob/master/spyder/widgets/browser.py#L290
