### ISSUE TITLE
Terminal content not re-scaling to plugin size

### ISSUE THREAD

**Issue by imaluengo** [spyder-ide/spyder-terminal#48]
With the latest Qt 5.8.x and latest version of Spyder the terminal doesn't change its size to fit the window it is in. It throws this error while loading (which might just be the case that it is not loading properly):

    [...]
    spyder_terminal/widgets/terminalgui.py", line 50, in __init__
        self.view.page().contentsChanged.connect(self.contents_modified)
       AttributeError: 'WebPage' object has no attribute 'contentsChanged'

After chasing the error through the code, it seems it has to do with the Qt version. From the [Qt documentation](http://doc.qt.io/qt-5/qwebenginepage.html#signals) the signal from `QWebEnginePage`, `contentsChanged` does no longer exist but another one `contentsSizeChanged` does exist.

I've changed [Line 50 of terminalgui.py](https://github.com/spyder-ide/spyder-terminal/blob/master/spyder_terminal/widgets/terminalgui.py#L50) from

    self.view.page().contentsChanged.connect(self.contents_modified)

to:

    self.view.page().contentsSizeChanged.connect(self.contents_modified)

and it works fine now. I'm not even sure if it is what it is supposed to do. But either commenting or changing the line above seems to let the WebView load properly and to help it rendering the terminal full size. If not it crashes and it can't load properly.

**Comment by andfoy** [comment]
Thanks for the report, it will corrected on 0.1.1

**Comment by goanpeca** [comment]
@andfoy we might need to add this patch to qtpy

**Comment by andfoy** [comment]
Then we should ping @ccordoba12 ?

**Comment by ccordoba12** [comment]
I think this bug belongs here because it's something that can be handled with the `WEBENGINE` constant of `qtpy`.

**Comment by goanpeca** [comment]
@ccordoba12 I think this qualifies as a version specific patch on qtpy

**Comment by ccordoba12** [comment]
Ok, that way it could be picked up by any other project using `qtpy`.

@andfoy, please open a PR in `qtpy` about this. Please take a look to

https://github.com/spyder-ide/qtpy/blob/master/qtpy/_patch/qcombobox.py

to see how widgets are patched.

**Comment by andfoy** [comment]
I think we should delete that instruction from ``terminalgui.py``

**Comment by andfoy** [comment]
It's doing nothing right now
