### ISSUE TITLE
Server doesn't launch on Spyder startup

### ISSUE THREAD

**Issue by avylove** [spyder-ide/spyder-terminal#57]
## Description of your problem
The tornado server doesn't seem to launch on Spyder startup

Executing spyder_terminal/server/main.py after Spyder has started, I can connect to a terminal

**What steps will reproduce the problem?**

1. pip3 install --user spyder-terminal
2. Launch Spyder
3. Open terminal

**What is the expected output? What do you see instead?**
Should see a terminal, instead see:
This site can’t be reached
127.0.0.1 refused to connect.

**Please provide any additional information below**

## Versions and main components

* Terminal Version: xterm.js included with spyder-terminal
* Spyder Version: 3.1.4
* Python Version: 3.5.3
* Operating system: Fedora 25

**Comment by ccordoba12** [comment]
Thanks for reporting, I can confirm your bug.

@andfoy, we need to release version 0.1.2 this week to fix this problem.

**Comment by andfoy** [comment]
Unfortunately, I cannot reproduce this error. @ccordoba12 could you please remove pipe redirection on [spyder_terminal/terminalplugin.py#L63](https://github.com/spyder-ide/spyder-terminal/blob/master/spyder_terminal/terminalplugin.py#L63) and see what's the output? :-)

**Comment by ccordoba12** [comment]
Could you create a PR to make the server output to go to a file instead?

**Comment by andfoy** [comment]
Great idea! I will do it

**Comment by ccordoba12** [comment]
Thanks!!

**Comment by andfoy** [comment]
@avylove Could you please tell us if spyder-terminal v0.1.2 solves your problem?

**Comment by avylove** [comment]
Seems to be fixed. Only thing I noticed was the clear that is issued after the initial cd doesn't seem to do anything. Actually, clear just doesn't seem to work. Not sure if that's an xterm.js bug or not.

**Comment by andfoy** [comment]
@avylove Could you please post a screenshot?

**Comment by ccordoba12** [comment]
I think this is caused because we're trying to run commands in the console before the prompt is ready.

@andfoy, please open a new issue about it, so we don't forget to fix it in 0.2.
