### ISSUE TITLE
Don't start to create consoles until the server is up and running

### ISSUE THREAD

**Issue by ccordoba12** [spyder-ide/spyder-terminal#59]
@andfoy, you can use this code to keep pinging the server until it's up (at least for 10 secs) and if not, report an error:

https://github.com/spyder-ide/spyder-notebook/blob/master/spyder_notebook/utils/nbopen.py#L65-L70

**Comment by andfoy** [comment]
Should I report the error using a QMessageBox? Or though the console?

**Comment by ccordoba12** [comment]
A QMessageBox, as we do in `spyder-notebook`.

**Comment by goanpeca** [comment]
@ccordoba12 but the code you point to is blocking, it would be better to use a QTimer

**Comment by andfoy** [comment]
So, should I use a QTimer?

**Comment by ccordoba12** [comment]
Ok, please use a QTimer. We could what we're doing in the notebook then.
