### ISSUE TITLE
Implement basic web bash console using tornado and xterm.js

### ISSUE THREAD

**Issue by andfoy** [spyder-ide/spyder-terminal#6]
This terminal implementation should be compatible with the [xterm.js API](http://xtermjs.org/docs/api/Terminal/), besides, the terminal execution shall be asynchronous and non-blocking. Also it shall support POSIX compatible Operating Systems and Windows command execution.

**Comment by rlaverde** [comment]
I came across this package https://ergonomica.github.io/ I think It could be a good option but maybe It's out of the scope of this plugin.

**Comment by ccordoba12** [comment]
@rlaverde, we need a real shell to use here. This means, a shell that can run Vim or Emacs inside it.

And I doubt Ergonomica or Xonsh have those capabilities :-)

**Comment by andfoy** [comment]
@rlaverde, @ccordoba12 is right, We need a full featured system console to execute external commands that are not defined on Python neither on Spyder
