### ISSUE TITLE
Capture all keyboard events when a console is on focus

### ISSUE THREAD

**Issue by andfoy** [spyder-ide/spyder-terminal#61]
Right now, some shortcuts are interfering with key presses aimed to the console. For instance, to exit ``htop`` we need to press ``F10``, however when that key is pressed, the shortcut that activates the code profiler is activated.

**Comment by ccordoba12** [comment]
That's because `F10` is a global shortcut. So #63 solves this?

**Comment by andfoy** [comment]
Actually, we would like to capture all key input, which means that ``F1`` or any key combination will be grabbed by the actual selected console, the only exception is ``Ctrl+Shift+Alt+T``, which creates new tabs.

**Comment by andfoy** [comment]
I think #63 is working

**Comment by ccordoba12** [comment]
Ok, please merge it then.
