### ISSUE TITLE
clear command does not work

### ISSUE THREAD

**Issue by avylove** [spyder-ide/spyder-terminal#72]
The clear command does not seem to function. I'm not sure if this is a xterm.js bug or a spyder-terminal bug.

**What steps will reproduce the problem?**

1. Launch terminal

**What is the expected output? What do you see instead?**
￼
Expected:

``` console
[avylove@localhost Project]$      
```
Actual:
``` console
Loading...                              
[avylove@localhost Project]$ cd /home/avram/Desktop/Audrey      
[avylove@localhost Project]$ clear
[avylove@localhost Project]$
```
**Please provide any additional information below**
Neither clear nor reset commands seem to do anything. I tried changing the clearTerm() function from to user term.clear(), which removed the clear command from the terminal, but still didn't clear the terminal.

## Versions and main components

* Terminal Version: Included
* Spyder Version: 0.1.2
* Python Version: 3.5.3
* Operating system: Fedora 25

**Comment by ccordoba12** [comment]
@avylove, thanks for opening the issue.

**Comment by andfoy** [comment]
@avylove Does PR #78 fixes your problem?

**Comment by avylove** [comment]
It doesn't seem to. Both this version and the original one work fine when launched outside of Spyder, but don't work both during initialization and if I open additional terminals once Spyder is up.

**Comment by andfoy** [comment]
Does the console output keeps the same?

**Comment by avylove** [comment]
Yes, same output.

**Comment by ccordoba12** [comment]
No, the idea is to clean all console output and leave only a single 
prompt on it. That's how %clear works on Linux/Mac, but does not on Windows.

**Comment by andfoy** [comment]
Does this happens only with the first console, or does it also happens with new terminal tabs?

**Comment by avylove** [comment]
New terminal tabs as well

**Comment by andfoy** [comment]
@avylove Does PR #93 fixes your problem?

**Comment by avylove** [comment]
Well I have mixed news. Turns out the issue must have been in Spyder because I don't have the issue with 0.1.2 when I bootstrap Spyder 3.x. Wish I had thought to do that before. I found this out because I installed the spyder-terminal master branch and didn't have the spyder-terminal plugin available in Spyder, so I thought maybe there was a dependency on the latest. Well it didn't work there either. Not sure what the issue is. How do I see some output?

**Comment by andfoy** [comment]
Have you tried to open an internal console and see if there is some output there?

**Comment by avylove** [comment]
First thing I tried. Nothing there.

**Comment by andfoy** [comment]
How did you installed the plugin?

**Comment by andfoy** [comment]
Is the plugin visible? Sometimes the plugin might be not be shown because its visibility is disabled

**Comment by avylove** [comment]
It wasn't visible or on the panes menu. I just realized I was using your fork instead of the master branch. Trying with the master branch now and having issues with bower not being in the path. Installing with pip. Added --no-deps because it was failing with the Spyder version. Spyder isn't installed, just launching with bootstap script.

``` console
pip3 install --user --no-deps git+https://github.com/spyder-ide/spyder-terminal.git
```

Is there a better way to go about this?

**Comment by andfoy** [comment]
Well, to install bower, you just need to execute:
```bash
npm install -g bower
```

**Comment by andfoy** [comment]
I would prefer to emit the following commands:
```bash
# From spyder master branch
python setup.py install

# From spyder-terminal master branch
pip install -U .
```

**Comment by avylove** [comment]
Well I don't install things globally that aren't in rpms, but I did run:
``` bash
npm install bower
```
Then I added ~/node_modules/.bin to my PATH. It installed and everything looks fine with spyder-terminal@master and spyder@3.x.

**Comment by andfoy** [comment]
@avylove Great to hear that is working!

**Comment by andfoy** [comment]
Release v0.2 of spyder-terminal will come on the following days
