### ISSUE TITLE
Copy and Paste shortcuts are disabled

### ISSUE THREAD

**Issue by andfoy** [spyder-ide/spyder-terminal#76]

**Comment by andfoy** [comment]
Now that we capture all keyboard inputs, is it possible to hardcode ``Ctrl+Shift+C/V`` to copy/paste text inside a terminal, this is the default shortcut on most Linux terminals @ccordoba12

**Comment by ccordoba12** [comment]
Sure, +1 from to this one.

**Comment by goanpeca** [comment]
>Now that we capture all keyboard inputs, is it possible to hardcode Ctrl+Shift+C/V to copy/paste text inside a terminal, this is the default shortcut on most Linux terminals @ccordoba12

Is this also valid for other languages?

**Comment by andfoy** [comment]
@goanpeca Are you referring to other terminals?

**Comment by goanpeca** [comment]
>@goanpeca Are you referring to other terminals?

No, I am referring to the case of French, German, Japanese, Chinese. Word/Office on different languages uses different shortcuts( Ctrl+S Ctrl+G for saving on english/Spanish), so I am asking if this could happen with terminals as well.

**Comment by andfoy** [comment]
As ``Ctrl+C`` and ``Ctrl+V`` are language agnostic, we can assume that ``Ctrl+Shift+C/V`` are agnostic as well

**Comment by andfoy** [comment]
We can't use ``Ctrl+C`` and ``Ctrl+V``, as they are keyboard escape sequences
