### ISSUE TITLE
Release 0.2

### ISSUE THREAD

**Issue by andfoy** [spyder-ide/spyder-terminal#84]

**Comment by andfoy** [comment]
@ccordoba12 Should 0.2 be released after Spyder 3.2 release?

**Comment by ccordoba12** [comment]
Yes. Right now I'm also working on a couple of PRs with installation fixes and minor UI improvements for spyder-terminal.

**Comment by ccordoba12** [comment]
Note: Don't forget to update version in setup.py from `3.2.0.dev0` to `3.2`

**Comment by ccordoba12** [comment]
@andfoy, I plan to release 0.2 tomorrow, during the SciPy sprints.

So I have two questions for you:

1. Can you be around tomorrow morning to do the release along with you?
2. Did you upload the `pywinpty` wheels to PyPi already?

**Comment by andfoy** [comment]
1. Yes, I'll available during the morning, at what time you'll release 0.2?
2. No, I haven't upload them yet.

**Comment by ccordoba12** [comment]
1. Please be between 10 and 12 on Flowdock. I'll be there too, but I have to release Spyder 3.2 first.
2. Tomorrow, while I'm releasing 3.2, please do the same for pywinpty, so that afterwards we can release 0.2.
