### ISSUE TITLE
Package missing in current win-64 channels

### ISSUE THREAD

**Issue by eliot1785** [spyder-ide/spyder-terminal#92]
## Description of your problem

**What steps will reproduce the problem?**

Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\myname>conda install spyder_terminal -c spyder-ide
Fetching package metadata ...............

PackageNotFoundError: Package missing in current win-64 channels:
  - spyder_terminal

**What is the expected output? What do you see instead?**

Expect successful install

**Please provide any additional information below**

Maybe you've only released 32-bit so far?

I'm not sure why it wouldn't be found since I was specifying your custom channel. 

## Versions and main components

* Terminal Version: not installed
* Spyder Version: 3.1.4
* Python Version: 3.6.1 64bits
* Operating system: Windows 7

**Comment by andfoy** [comment]
@eliot1785 Sorry, we haven't published our conda packages yet, they will be available on the coming days

**Comment by andfoy** [comment]
But you can install pywinpty via conda and install spyder-terminal from sources

**Comment by andfoy** [comment]
``conda install pywinpty -c spyder-ide``

**Comment by andfoy** [comment]
Windows packages are now available at: https://anaconda.org/spyder-ide/spyder-terminal
